pie-framework/pie-elements

- packages/categorize/configure/src/design/buttons.jsx
- packages/categorize/configure/src/design/categories/index.jsx
- packages/categorize/configure/src/design/choices/config.jsx
- packages/categorize/configure/src/design/choices/index.jsx
- packages/categorize/configure/src/design/header.jsx
- packages/categorize/configure/src/design/index.jsx
- packages/categorize/docs/demo/generate.js
Re-work the layout of elements, fix inputs, fix grid system and various other small updates
@evaneus not 100% as described in the ticket, but I've attached a screenshot, let me know what you think. I tried to make the component be more in-line with the corespring one. I also played around with the spacings a little to make it generally look a lot better than it used to.
Please let me know what you think!
> feature(categorize): updates

- packages/extended-text-entry/configure/package.json
- packages/multiple-choice/configure/package.json
- yarn.lock
This should fix [Issue 82](https://github.com/pie-framework/pie-elements/issues/82)
> fix(editable-html-package-update): updated the editable-html version

- packages/categorize/configure/src/design/choices/config.jsx
This needs to be update with the new `@pie-ui/categorize` version after [this](https://github.com/pie-framework/pie-ui/pull/23) PR is merged.
> feat(issue-84): changed label title and added position left and right for the choices

- packages/select-text/configure/package.json
- packages/select-text/configure/src/__tests__/__snapshots__/design.test.jsx.snap
- packages/select-text/configure/src/__tests__/design.test.jsx
- packages/select-text/configure/src/design.jsx
- packages/select-text/docs/demo/generate.js
- yarn.lock
This needs to be updated and merged only after [this](https://github.com/pie-framework/pie-lib/pull/39) pr is merged.
> feat(mode-display): displayed the mode for the tokenizer

- packages/match/configure/src/answer-config-block.jsx
- packages/match/configure/src/configure.jsx
- packages/match/configure/src/index.js
- packages/match/configure/src/row.jsx
This needs to be merged after the [pie-lib](https://github.com/pie-framework/pie-lib/pull/40) and [pie-ui](https://github.com/pie-framework/pie-ui/pull/25) PR's are merged
> feat(ch467): changed the regular input to an editable-html component and added image support

- packages/match/configure/package.json
- packages/match/configure/src/configure.jsx
- packages/match/configure/src/row.jsx
- packages/match/controller/src/__tests__/index.test.jsx
- packages/match/controller/src/index.js
- packages/match/docs/demo/config.js
- packages/multiple-choice/configure/package.json
- packages/multiple-choice/configure/src/main.jsx
- packages/multiple-choice/controller/src/__tests__/index.test.js
- packages/multiple-choice/controller/src/index.js
- packages/multiple-choice/docs/demo/generate.js
- packages/select-text/configure/package.json
- packages/select-text/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/select-text/configure/src/__tests__/main.test.jsx
- packages/select-text/configure/src/main.jsx
- packages/select-text/controller/src/__tests__/index.test.js
- packages/select-text/controller/src/index.js
- packages/select-text/docs/demo/generate.js
- yarn.lock
@edeustace 
Needs to be merged only after [this](https://github.com/pie-framework/pie-lib/pull/43) pr is merged.
> feat(ch497): updated the partial scoring for 3 packages: match, select-text and multiple-choice

- packages/select-text/configure/package.json
- packages/select-text/configure/src/__tests__/__snapshots__/design.test.jsx.snap
- packages/select-text/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/select-text/configure/src/__tests__/design.test.jsx
- packages/select-text/configure/src/defaultConfiguration.js
- packages/select-text/configure/src/design.jsx
- packages/select-text/configure/src/index.js
- packages/select-text/configure/src/main.jsx
- packages/select-text/controller/src/index.js
- packages/select-text/docs/demo/generate.js
- packages/select-text/package.json
- yarn.lock
Needs to be merged only after [this](https://github.com/pie-framework/pie-ui/pull/27) is merged.
> feat(select-text-configure-customization): made it possible to customize the elements from the config design, updated tests

- packages/match/configure/package.json
- packages/match/configure/src/answer-config-block.jsx
- packages/match/controller/package.json
- packages/multiple-choice/controller/src/index.js
- packages/placement-ordering/configure/package.json
- packages/select-text/configure/package.json
- packages/select-text/configure/src/index.js
This pr needs to be merged only after [this](https://github.com/pie-framework/pie-lib/pull/49) one is merged.
> fix(dependencies-add): added dependencies where needed

- packages/multiple-choice/configure/src/__tests__/root.test.jsx
- packages/multiple-choice/configure/src/index.js
- packages/multiple-choice/configure/src/root.jsx
Fixing [this](https://github.com/pie-framework/pie-elements/issues/78)
> fix(multiple-choice-item-preview-reset): resetting the item preview when changing response type

- .gitignore
- packages/select-text/controller/src/__tests__/index.test.js
- packages/select-text/controller/src/index.js
- packages/select-text/docs/demo/config.js
- packages/select-text/docs/demo/generate.js
- packages/select-text/docs/demo/index.html
- packages/select-text/package.json
* This was added to @pie-ui/select-text@^1.4.0 ->
@pie-lib/text-select@^1.4.0.
> feat: Support markup + mathml rendering in select-text

- packages/extended-text-entry/configure/package.json
- yarn.lock
Updated @pie-lib/config-ui and @pie-lib/editable-html versions.
(pie-lib/config-ui contains a fix for allowing the number text field to be edited)
(pie-lib/editable-html contains a fix to resize properly the question prompt dimensions and a fix for equation-editor)
> fix(package.json)

- packages/calculator/configure/package.json
- packages/categorize/configure/package.json
- packages/function-entry/configure/package.json
- packages/inline-choice/configure/package.json
- packages/number-line/configure/package.json
- packages/point-intercept/configure/package.json
- packages/ruler/configure/package.json
- packages/select-text/configure/package.json
- packages/text-entry/configure/package.json
- yarn.lock
fix(categorize): Updated @pie-lib/config-ui version.
fix(function-entry): Updated @pie-lib/config-ui version.
fix(inline-choice): Updated @pie-lib/config-ui version.
fix(number-line): Updated @pie-lib/config-ui version.
fix(point-intercept): Updated @pie-lib/config-ui version.
fix(ruler): Updated @pie-lib/config-ui version.
fix(select-text): Updated @pie-lib/config-ui version.
fix(text-entry): Updated @pie-lib/config-ui version.
> fix(calculator): Updated @pie-lib/config-ui version.

- packages/ebsr/docs/demo/generate.js
- packages/pie-models/src/pie/multiple-choice/index.ts
- packages/pie-models/src/pie/placement-ordering/index.ts
- packages/placement-ordering/configure/src/__tests__/__snapshots__/design.test.jsx.snap
- packages/placement-ordering/configure/src/__tests__/design.test.jsx
- packages/placement-ordering/configure/src/defaults.js
- packages/placement-ordering/configure/src/design.jsx
- packages/placement-ordering/controller/src/__tests__/index.test.js
- packages/placement-ordering/controller/src/defaults.js
- packages/placement-ordering/controller/src/index.js
- packages/placement-ordering/docs/demo/generate.js
fix(ebsr): revert `itemStem` to `prompt`.
fix(multiple-choice): revert `itemStem` to `prompt`.
fix(placement-ordering): revert `itemStem` to `prompt`.
> revert `itemStem` to `prompt`.

- packages/hotspot/configure/src/hotspot-container.jsx
- packages/hotspot/configure/src/hotspot-drawable.jsx
- packages/hotspot/configure/src/root.jsx
- packages/hotspot/configure/src/upload-control.jsx
- packages/hotspot/controller/src/index.js
Implement rendering support for legacy content with correct answers defined as polygon. 
See more details [here](https://app.clubhouse.io/keydatasystems/story/1616/hotspot-support-rendering-for-legacy-content-with-correct-answers-defined-as-polygon).
> feat: hotspot rendering support for polygons

- packages/math-inline/controller/src/__tests__/index.test.jsx
- packages/math-inline/controller/src/index.js
> fix(math-inline): validation logic fix for allowSpaces

- packages/match/controller/src/__tests__/index.test.jsx
- packages/match/controller/src/index.js
Issue presented [here](https://app.clubhouse.io/keydatasystems/story/2697/match-partial-credit-scoring-produces-incorrect-scores-for-radio-button-based-items).
> fix: calculate correct scoring for radios

- packages/categorize/configure/package.json
- packages/categorize/controller/package.json
- packages/drag-in-the-blank/configure/package.json
- packages/drag-in-the-blank/controller/package.json
- packages/drawing-response/configure/package.json
- packages/ebsr/configure/package.json
- packages/explicit-constructed-response/configure/package.json
- packages/explicit-constructed-response/controller/package.json
- packages/extended-text-entry/configure/package.json
- packages/hotspot/configure/package.json
- packages/hotspot/controller/package.json
- packages/image-cloze-association/controller/package.json
- packages/inline-choice/configure/package.json
- packages/inline-dropdown/configure/package.json
- packages/inline-dropdown/controller/package.json
- packages/multiple-choice/configure/package.json
- packages/multiple-choice/controller/package.json
- packages/number-line/controller/package.json
- packages/pie-models/package.json
- packages/placement-ordering/configure/package.json
- packages/placement-ordering/controller/package.json
- packages/select-text/configure/package.json
- packages/select-text/controller/package.json
Should take care of the security vulnerability that github detected.
> chore: lodash version bump

- packages/image-cloze-association/controller/src/__tests__/index.test.js
- packages/image-cloze-association/controller/src/index.js
Original description [here](https://app.clubhouse.io/keydatasystems/story/1955/ica-alternate-correct-answers).
> feat: support alternate correct answers

- packages/ebsr/configure/src/index.js
Issue reported [here](https://app.clubhouse.io/keydatasystems/story/2916/ebsr-certain-changes-to-the-settings-panel-crash-the-player).
> fix: settings should work as expected

- packages/rubric/src/__tests__/rubric-view.test.jsx
- packages/rubric/src/main.jsx
> fix(rubric): fix exclude zeroes number of points

- packages/categorize/configure/src/design/__tests__/__snapshots__/index.test.jsx.snap
- packages/categorize/configure/src/design/index.jsx
- packages/match/configure/src/configure.jsx
- packages/number-line/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/number-line/configure/src/main.jsx
As discussed with George, these no longer make sense. This kind of documentation / assistance will be handled elsewhere.
> chore: remove dummy prompts for various interactions

- packages/hotspot/configure/src/hotspot-container.jsx
- packages/hotspot/configure/src/hotspot-drawable.jsx
- packages/hotspot/configure/src/hotspot-palette.jsx
- packages/hotspot/configure/src/hotspot-rectangle.jsx
should fix [3536](https://app.clubhouse.io/keydatasystems/story/3536/console-errors-for-hotspot)
> fix console errors

- packages/ebsr/configure/src/defaults.js
- packages/ebsr/configure/src/index.js
- packages/ebsr/configure/src/main.jsx
- packages/ebsr/controller/src/__tests__/index.test.js
- packages/ebsr/controller/src/__tests__/utils.test.js
- packages/ebsr/controller/src/index.js
- packages/ebsr/docs/pie-schema.json
- packages/ebsr/docs/pie-schema.json.md
- packages/pie-models/src/pie/ebsr/index.ts
Added feedbackEnabled property on model.
> fix: Do not use e.update if it is not defined.

- packages/math-inline/controller/src/__tests__/index.test.jsx
- packages/math-inline/controller/src/index.js
> fix(math-inline): simple mode literal evaluation fix for decimals and spaces

- packages/math-inline/controller/src/__tests__/index.test.jsx
- packages/math-inline/controller/src/index.js
> fix(math-inline): fix symbolic evaluation with text nodes - ch4709

- packages/math-inline/controller/src/index.js
> fix(math-inline): fix controller logic safety net - ch3905

- packages/multiple-choice/controller/src/__tests__/index.test.js
- packages/multiple-choice/controller/src/index.js
feedbackEnabled should not be the property that decides whether the choice correctness is displayed or not.
> fix: feedbackEnabled 

- packages/drawing-response/configure/src/__tests__/__snapshots__/image-container.test.jsx.snap
- packages/drawing-response/configure/src/__tests__/__snapshots__/root.test.jsx.snap
- packages/drawing-response/configure/src/__tests__/image-container.test.jsx
- packages/drawing-response/configure/src/__tests__/root.test.jsx
- packages/drawing-response/configure/src/image-container.jsx
- packages/drawing-response/configure/src/index.js
- packages/drawing-response/configure/src/root.jsx
- packages/drawing-response/controller/src/__tests__/index.test.js
- packages/extended-text-entry/configure/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/configure/src/__tests__/main.test.js
- packages/extended-text-entry/configure/src/index.js
- packages/extended-text-entry/configure/src/main.jsx
- packages/extended-text-entry/controller/src/__tests__/index.test.js
- packages/inline-choice/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/inline-choice/configure/src/__tests__/__snapshots__/root.test.jsx.snap
- packages/inline-choice/configure/src/__tests__/main.test.jsx
- packages/inline-choice/configure/src/__tests__/root.test.jsx
- packages/inline-choice/configure/src/root.jsx
- packages/inline-choice/controller/src/__tests__/index.test.js
- packages/inline-choice/controller/src/index.js
tests for:
- drawing-response
- extended-text-entry
- inline-choice
> Added tests.

- packages/ebsr/controller/src/__tests__/index.test.js
- packages/ebsr/controller/src/index.js
Show correct answer functionality is wrong for the EBSR item (feedback does not have to be enabled in order to determine if an answer is correct or not).
> fix: pie-228: Item Authoring

- packages/hotspot/configure/src/__tests__/__snapshots__/hotspot-container.test.js.snap
- packages/hotspot/configure/src/__tests__/__snapshots__/hotspot-drawable.test.js.snap
- packages/hotspot/configure/src/__tests__/__snapshots__/root.test.js.snap
- packages/hotspot/configure/src/__tests__/hotspot-container.test.js
- packages/hotspot/configure/src/__tests__/hotspot-drawable.test.js
- packages/hotspot/configure/src/__tests__/index.test.js
- packages/hotspot/configure/src/__tests__/root.test.js
- packages/hotspot/configure/src/hotspot-container.jsx
- packages/hotspot/configure/src/hotspot-drawable.jsx
- packages/hotspot/configure/src/hotspot-polygon.jsx
- packages/hotspot/configure/src/index.js
- packages/hotspot/configure/src/root.jsx
- packages/hotspot/controller/src/index.js
- packages/hotspot/docs/demo/generate.js
- packages/hotspot/docs/demo/session.js
- display them
- possibility to mark/unmark as correct
- possibility to drag/drop
> feat: added support for declared polygons:

- packages/inline-dropdown/configure/src/markupUtils.js
> feat(markup): sanity checked the choices [ch5774]

- packages/math-inline/configure/src/response.jsx
- packages/math-inline/controller/src/__tests__/index.test.jsx
- packages/math-inline/controller/src/index.js
- packages/math-inline/docs/demo/generate.js
Solves [ch3679] and we hope a lot of others too, at least partially!
> feat(math-inline): string-based check for evaluation, invalid latex command support

- packages/math-inline/configure/package.json
- packages/math-inline/controller/package.json
- packages/math-inline/controller/src/__tests__/index.test.jsx
- packages/math-inline/controller/src/index.js
- yarn.lock
I have a better version of this PR - but this one is simpler and builds off develop.
> fix: ch6456 - handle %

- packages/math-inline/controller/src/__tests__/index.test.jsx
- packages/math-inline/controller/src/index.js
- packages/math-inline/docs/demo/generate.js
- packages/math-inline/docs/demo/session.js
@elodszopos - this makes the test pass.. run: 
./node_modules/.bin/jes packages/math-inline/controller/src/__tests__/index.test.jsx --watch
Note that I'm not handling any mismatch between the expression and the correct answer in terms of white space. Is that something that needs to be handled?
> 7165 math inline

- packages/charting/controller/src/__tests__/index.test.js
- packages/charting/controller/src/index.js
Partial credit scoring is not working for Charting items.
> fix: ch3979: use correctAnswer in evaluate mode 

- packages/hotspot/controller/src/__tests__/index.test.js
- packages/hotspot/controller/src/index.js
- packages/hotspot/controller/src/utils.js
Hot spot scoring problem in IBX (legacy content with multiple correct answers
> fix: ch7555: selecting answers in a different order was not working 

- packages/graphing/controller/src/__tests__/index.test.js
- packages/graphing/controller/src/index.js
> Fixed scoring for parabola.

- packages/hotspot/configure/src/__tests__/hotspot-drawable.test.js
- packages/hotspot/configure/src/hotspot-drawable.jsx
Double-clicking image crashes Build screen
> fix: ch7720: Authoring problem with Hotspot: 

- packages/drag-in-the-blank/configure/src/__tests__/__snapshots__/choices.test.jsx.snap
- packages/drag-in-the-blank/configure/src/__tests__/choices.test.jsx
- packages/drag-in-the-blank/configure/src/choices.jsx
- packages/drag-in-the-blank/docs/demo/generate.js
the "Add Choice" button has no apparent effect.
> fix: ch7653: In IBX Item Authoring, for Drag in the Blank

- packages/hotspot/configure/src/__tests__/__snapshots__/hotspot-container.test.js.snap
- packages/hotspot/configure/src/__tests__/__snapshots__/hotspot-drawable.test.js.snap
- packages/hotspot/configure/src/__tests__/__snapshots__/root.test.js.snap
- packages/hotspot/configure/src/__tests__/hotspot-container.test.js
- packages/hotspot/configure/src/__tests__/hotspot-drawable.test.js
- packages/hotspot/configure/src/__tests__/index.test.js
- packages/hotspot/configure/src/__tests__/root.test.js
- packages/hotspot/configure/src/__tests__/utils.test.js
- packages/hotspot/configure/src/hotspot-container.jsx
- packages/hotspot/configure/src/hotspot-drawable.jsx
- packages/hotspot/configure/src/index.js
- packages/hotspot/configure/src/root.jsx
- packages/hotspot/configure/src/utils.js
- packages/hotspot/controller/src/index.js
- packages/hotspot/docs/demo/generate.js
fix: PD-56: Bug with resizing an image in hot spot
fix: PD-57: Hotspot: Enlarge the Help icon
fix: PD-58: Hotspot: Hotspot creation should use a drag-and-drop gesture to create hotspots.
> Fixes for HOTSPOT

- packages/math-inline/controller/src/__tests__/index.test.jsx
1. Added test cases to check whether there is issue with math-line equation full score.
> test: Added test cases for PD-610

- packages/multiple-choice/configure/src/defaults.js
- packages/multiple-choice/configure/src/main.jsx
- packages/multiple-choice/docs/config-schema.json
- packages/multiple-choice/docs/config-schema.json.md
- packages/multiple-choice/docs/pie-schema.json
- packages/multiple-choice/docs/pie-schema.json.md
Draft for now - need to verify EBSR and other interaction types impact before moving forward.
> feat(multiple-choice): add maximum number of choices toggle and related logic

- packages/math-inline/configure/src/general-config-block.jsx
https://illuminate.atlassian.net/browse/PD-893
> fix(math-inline): fix editor width to contain button - PD-893

- packages/categorize/controller/src/__tests__/index.test.js
- packages/categorize/controller/src/index.js
wait for getCorrectness in order to update correctness and feedback for player output
> fix(categorize): show feedback for player-PD-899

- packages/categorize/configure/src/design/categories/droppable-placeholder.jsx
https://illuminate.atlassian.net/secure/RapidBoard.jspa?rapidView=439&modal=detail&selectedIssue=PD-894&quickFilter=1805&assignee=601120f0c8c36c0069681445&assignee=5d4af50dba09fa0c50c60de8
> fix(categorize): fix height for droppable-placeholder - PD-894

- packages/select-text/configure/src/__tests__/utils.test.jsx
- packages/select-text/configure/src/index.js
- packages/select-text/configure/src/utils.js
- packages/select-text/docs/demo/config.js
- packages/select-text/docs/demo/generate.js
- packages/select-text/docs/demo/index.html
PD-134: feat(tokens): made sure paragraphs and new lines are working in select text
> PD-134: feat(tokens): made sure paragraphs and new lines are working in select text

- packages/drawing-response/configure/src/__tests__/__snapshots__/root.test.jsx.snap
- packages/drawing-response/configure/src/root.jsx
- packages/hotspot/configure/src/__tests__/__snapshots__/root.test.js.snap
- packages/hotspot/configure/src/root.jsx
https://illuminate.atlassian.net/browse/PD-61
> fix: hotspot and drawing response settings panel sections to fix PD-61

- packages/graphing/configure/src/__tests__/index.test.js
- packages/graphing/configure/src/index.js
- packages/graphing/controller/src/__tests__/index.test.js
- packages/graphing/controller/src/__tests__/utils.test.js
- packages/graphing/controller/src/index.js
- packages/graphing/controller/src/utils.js
https://illuminate.atlassian.net/browse/PD-784
> fix(graphing): add correctResponse first in answers array & show correctResponse if there is no better alternate response  PD-784

- packages/extended-text-entry/controller/src/defaults.js
- packages/extended-text-entry/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-694
> fix(extended-text-entry): add default dimensions to fix PD-694

- packages/multiple-choice/controller/src/index.js
> Fix(multi-choice): controller: fix sanity check

- packages/graphing/configure/src/__tests__/__snapshots__/correct-response.test.js.snap
- packages/graphing/configure/src/__tests__/correct-response.test.js
- packages/graphing/configure/src/correct-response.jsx
https://illuminate.atlassian.net/browse/PD-790
> (graphing): add sanity checks and tests

- packages/placement-ordering/configure/src/__tests__/index.test.jsx
- packages/placement-ordering/configure/src/index.js
- packages/placement-ordering/docs/demo/generate.js
> fix(placement-ordering): provide an array of objects containing {key, weight}  as expected in correctResponse

- packages/ebsr/controller/src/defaults.js
- packages/ebsr/controller/src/index.js
- packages/multiple-choice/controller/src/__tests__/index.test.js
https://illuminate.atlassian.net/browse/PD-591
> fix: ebsr use letter choicePrefixes as default PD-591

- packages/placement-ordering/controller/src/defaults.js
- packages/placement-ordering/controller/src/index.js
- packages/placement-ordering/src/__tests__/placement-ordering.test.jsx
- packages/placement-ordering/src/placement-ordering.jsx
https://illuminate.atlassian.net/browse/PD-527
> fix: If you return to an item with a separate target area the previously-entered response is seemingly lost. PD-527

- packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-207
> fix(math-inline): fix spacing bug with nth roots in response area PD-207

- packages/ebsr/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-909
> fix: EBSR authoring triggering console error PD-909

- packages/drawing-response/src/drawing-response/__tests__/__snapshots__/drawing-main.test.jsx.snap
- packages/drawing-response/src/drawing-response/__tests__/drawing-main.test.jsx
- packages/drawing-response/src/drawing-response/drawable-main.jsx
https://illuminate.atlassian.net/browse/PD-263
> fix(drawing-response): remove console error PD-263

- packages/number-line/src/number-line/graph/index.jsx
https://illuminate.atlassian.net/browse/PD-471
> fix: In a number line item with very large (5-digit) numeric labels, the labels are partially cut off PD-471

- packages/match/src/answer-grid.jsx
https://illuminate.atlassian.net/browse/PD-933
> fix(match): decrease vertical spacing PD-933

- packages/passage/src/stimulus-tabs.jsx
https://illuminate.atlassian.net/browse/PD-611
> fix(passage): preserve non-breaking spaces in content in order to make indentation visible PD-611

- packages/extended-text-entry/configure/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/configure/src/defaults.js
- packages/extended-text-entry/configure/src/main.jsx
- packages/extended-text-entry/controller/src/__tests__/index.test.js
- packages/extended-text-entry/controller/src/index.js
- packages/extended-text-entry/docs/pie-schema.json
- packages/extended-text-entry/docs/pie-schema.json.md
- packages/math-inline/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/math-inline/configure/src/general-config-block.jsx
- packages/math-inline/configure/src/response.jsx
- packages/math-inline/controller/src/__tests__/index.test.jsx
- packages/math-inline/docs/pie-schema.json
- packages/math-inline/docs/pie-schema.json.md
- packages/math-inline/src/__tests__/__snapshots__/main.test.js.snap
- packages/math-inline/src/__tests__/main.test.js
- packages/math-inline/src/__tests__/simple-question-block.test.js
- packages/math-inline/src/main.jsx
- packages/pie-models/src/pie/extended-text-entry/index.ts
- packages/pie-models/src/pie/math-inline/index.ts
https://illuminate.atlassian.net/browse/PD-870
> fix/PD-870 Rename the "Everything" math editor as the "Miscellaneous" math editor

- packages/ebsr/configure/src/index.js
- packages/ebsr/configure/src/main.jsx
https://illuminate.atlassian.net/browse/PD-262
> fix(ebsr): set only one correct answer when controls are switched from checkbox to radio button PD-262

- packages/number-line/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/number-line/configure/src/__tests__/main.test.jsx
- packages/number-line/configure/src/main.jsx
- packages/number-line/src/__tests__/index.test.jsx
- packages/number-line/src/index.js
- packages/number-line/src/number-line/index.jsx
- packages/number-line/src/number-line/point-chooser/button.jsx
- packages/number-line/src/number-line/point-chooser/index.jsx
- packages/number-line/src/number-line/point-chooser/styles.js
https://illuminate.atlassian.net/browse/PD-498
> feat(number-line): Add Undo and Clear All buttons - PD-498

- packages/match/src/answer-grid.jsx
https://illuminate.atlassian.net/browse/PD-933
> fix(match): decrease vertical padding PD-933

- packages/charting/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/charting/configure/src/defaults.js
https://illuminate.atlassian.net/browse/PD-1016
> fix(charting): remove step & labelStep from default model PD-1016

- packages/pie-models/src/index.ts
- packages/pie-models/src/pie/rubric/index.ts
- packages/rubric/controller/src/__tests__/index.test.js
- packages/rubric/docs/config-schema.json
- packages/rubric/docs/config-schema.json.md
- packages/rubric/docs/demo/generate.js
- packages/rubric/docs/pie-schema.json
- packages/rubric/docs/pie-schema.json.md
- packages/rubric/src/__tests__/__snapshots__/rubric-view.test.jsx.snap
- packages/rubric/src/__tests__/rubric-view.test.jsx
- packages/rubric/src/main.jsx
https://illuminate.atlassian.net/browse/PD-621
> feat(rubric): Added sample answers to the model - PD-621

- packages/multi-trait-rubric/configure/src/__tests__/__snapshots__/scale.test.jsx.snap
- packages/multi-trait-rubric/configure/src/__tests__/__snapshots__/trait.test.jsx.snap
- packages/multi-trait-rubric/configure/src/__tests__/__snapshots__/traitsHeader.test.jsx.snap
- packages/multi-trait-rubric/configure/src/common.jsx
- packages/multi-trait-rubric/configure/src/trait.jsx
- packages/multi-trait-rubric/configure/src/traitsHeader.jsx
- packages/multi-trait-rubric/configure/src/utils.js
- packages/multi-trait-rubric/src/scale.jsx
https://illuminate.atlassian.net/browse/PD-1107
> feat: multi-trait-rubric update ui PD-1107

- packages/image-cloze-association/src/possible-response.jsx
https://illuminate.atlassian.net/browse/PD-1096
> fix(image-cloze-association): Fixed possible responses padding - PD-1096

- packages/match/src/answer-grid.jsx
https://illuminate.atlassian.net/browse/PD-781
> fix(match): Changed the horizontal spacing - PD-781

- packages/inline-dropdown/configure/src/inline-dropdown-toolbar.jsx
- packages/inline-dropdown/configure/src/main.jsx
https://illuminate.atlassian.net/browse/PD-294
> fix(inline-dropdown): Improved the UX when adding an answer choice PD-294

- packages/categorize/src/categorize/categories.jsx
- packages/categorize/src/categorize/choice.jsx
https://illuminate.atlassian.net/browse/PD-1141
> fix(categorize): Changed category labels font size - PD-1141

- packages/ebsr/configure/src/__tests__/__snapshots__/index.test.js.snap
- packages/ebsr/configure/src/defaults.js
- packages/ebsr/configure/src/main.jsx
- packages/ebsr/controller/src/index.js
- packages/ebsr/docs/config-schema.json
- packages/ebsr/docs/config-schema.json.md
- packages/ebsr/docs/pie-schema.json
- packages/ebsr/docs/pie-schema.json.md
- packages/multiple-choice/configure/src/defaults.js
- packages/pie-models/src/pie/ebsr/index.ts
Also displayed the toggle button for vertical mode in multiple-choice settings 
https://illuminate.atlassian.net/browse/PD-1144
> feat(ebsr): Added vertical/horizontal layout setting - PD-1144

- packages/number-line/controller/src/__tests__/index.test.js
- packages/number-line/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-448
> fix(number-line): partial scoring not working correctly PD-448

- packages/number-line/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/number-line/configure/src/defaults.js
- packages/number-line/controller/src/__tests__/index.test.js
- packages/number-line/controller/src/defaults.js
- packages/number-line/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-935
> fix(number-line): if feedback is not specified in the model, it is set to none PD-935

- packages/image-cloze-association/src/root.jsx
https://illuminate.atlassian.net/browse/PD-1099
> fix(image-cloze-association): Dragging a token from one container to other should move it - PD-1099

- packages/match/controller/src/__tests__/index.test.jsx
- packages/match/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-741
> feat(match): change partial scoring method for match items that use checkboxes PD-741

- packages/charting/src/__tests__/__snapshots__/main.test.js.snap
- packages/charting/src/main.jsx
https://illuminate.atlassian.net/browse/PD-403
> feat(charting): show correct functionality for evaluate mode PD-403

- packages/select-text/controller/src/__tests__/index.test.js
- packages/select-text/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-407
> fix(select-text): partial scoring not working correctly PD-407

- packages/number-line/src/number-line/graph/elements/point.jsx
https://illuminate.atlassian.net/browse/PD-1164
> feat(number-line): circles indicating an open interval should have a white fill PD-1164

- packages/categorize/configure/src/design/categories/__tests__/__snapshots__/index.test.jsx.snap
- packages/categorize/configure/src/design/categories/index.jsx
- packages/categorize/src/categorize/__tests__/__snapshots__/categories.test.jsx.snap
- packages/categorize/src/categorize/categories.jsx
- packages/categorize/src/categorize/index.jsx
https://illuminate.atlassian.net/browse/PD-197
> fix(categorize): Fixed Row labels appearance and the display of categories - PD-197

- packages/number-line/src/number-line/index.jsx
https://illuminate.atlassian.net/browse/PD-577
> fix(number-line): show correct should not display feedback PD-577

- packages/charting/controller/src/__tests__/index.test.js
- packages/charting/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-535
> fix(charting): Fixed student cannot edit category labels when required - PD-535

- packages/drawing-response/configure/src/__tests__/__snapshots__/root.test.jsx.snap
- packages/drawing-response/configure/src/__tests__/root.test.jsx
- packages/drawing-response/configure/src/defaults.js
- packages/drawing-response/configure/src/root.jsx
- packages/drawing-response/controller/src/__tests__/index.test.js
- packages/drawing-response/controller/src/index.js
- packages/drawing-response/docs/config-schema.json
- packages/drawing-response/docs/config-schema.json.md
- packages/drawing-response/docs/pie-schema.json
- packages/drawing-response/docs/pie-schema.json.md
- packages/pie-models/src/pie/drawing-response/index.ts
https://illuminate.atlassian.net/browse/PD-191
> feat(drawing-response): remove rationale PD-191

- packages/math-inline/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/math-inline/configure/src/general-config-block.jsx
https://illuminate.atlassian.net/browse/PD-334
> fix(math-inline): remove +response button from authoring PD-334

- packages/categorize/configure/src/design/__tests__/__snapshots__/input-header.test.jsx.snap
- packages/categorize/configure/src/design/input-header.jsx
- packages/drag-in-the-blank/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/drag-in-the-blank/configure/src/main.jsx
- packages/match/configure/src/row.jsx
- packages/multiple-choice/configure/src/main.jsx
- packages/placement-ordering/configure/src/choice-tile.jsx
- multiple-choice  -  remove buttons from choice rationales - will also affect ebsr
- drag-in-the-blank, categorize, placement-odering - remove buttons from choices
- match - remove buttons from rows
https://illuminate.atlassian.net/browse/PD-1180
> feat: remove audio and video buttons from various fields of various items PD-1180

- packages/select-text/configure/src/design.jsx
https://illuminate.atlassian.net/browse/PD-475
> feat(select-text): disallow too small values for maxSelections PD-475

- packages/drag-in-the-blank/configure/src/__tests__/__snapshots__/choices.test.jsx.snap
- packages/drag-in-the-blank/configure/src/__tests__/choices.test.jsx
- packages/drag-in-the-blank/configure/src/choices.jsx
https://illuminate.atlassian.net/browse/PD-192
> feat(drag-in-the-blank): don't allow identical answer choices PD-192

- packages/number-line/src/number-line/index.jsx
https://illuminate.atlassian.net/browse/PD-474
> fix(number-line): Overwrite style for reboot PD-474

- packages/hotspot/controller/src/__tests__/index.test.js
- packages/hotspot/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-816
> fix(hotspot): partial scoring not working correctly PD-816

- packages/extended-text-entry/src/main.jsx
https://illuminate.atlassian.net/browse/PD-384
> fix(extended-text-entry): Removed main content padding PD-384

- packages/inline-dropdown/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/inline-dropdown/configure/src/defaults.js
- packages/inline-dropdown/configure/src/main.jsx
- packages/inline-dropdown/docs/demo/generate.js
- packages/inline-dropdown/docs/pie-schema.json
- packages/inline-dropdown/docs/pie-schema.json.md
- packages/pie-models/src/pie/inline-dropdown/index.ts
> feat(inline-dropdown) : added toolbar editor position option

- packages/categorize/configure/src/defaults.js
- packages/categorize/configure/src/design/__tests__/__snapshots__/index.test.jsx.snap
- packages/categorize/configure/src/design/categories/category.jsx
- packages/categorize/configure/src/design/categories/index.jsx
- packages/categorize/configure/src/design/choices/choice.jsx
- packages/categorize/configure/src/design/choices/index.jsx
- packages/categorize/configure/src/design/index.jsx
- packages/categorize/configure/src/design/input-header.jsx
- packages/categorize/docs/demo/generate.js
- packages/categorize/docs/pie-schema.json
- packages/categorize/docs/pie-schema.json.md
- packages/pie-models/src/pie/categorize/index.ts
> Feat(categorize)/toolbar editor position

- packages/ebsr/configure/src/defaults.js
- packages/ebsr/configure/src/index.js
- packages/ebsr/configure/src/main.jsx
- packages/ebsr/docs/demo/config.js
https://illuminate.atlassian.net/browse/PD-259
> feat(ebsr): Allowed Part A to be multiple select PD-259

- packages/select-text/configure/src/index.js
- packages/select-text/docs/demo/generate.js
https://illuminate.atlassian.net/browse/PD-1235
> fix(select-text): fix initial view of tokens in authoring PD-1235

- packages/pie-models/src/pie/placement-ordering/index.ts
- packages/placement-ordering/docs/pie-schema.json
- packages/placement-ordering/docs/pie-schema.json.md
https://illuminate.atlassian.net/browse/PD-305
> fix(placement-ordering): Updated documentation PD-305

- packages/multi-trait-rubric/configure/src/__tests__/__snapshots__/scale.test.jsx.snap
- packages/multi-trait-rubric/configure/src/__tests__/__snapshots__/traitsHeader.test.jsx.snap
- packages/multi-trait-rubric/configure/src/common.jsx
- packages/multi-trait-rubric/configure/src/scale.jsx
- packages/multi-trait-rubric/configure/src/traitsHeader.jsx
https://illuminate.atlassian.net/browse/PD-1238
> fix(multi-trait-rubric): Fixed the score point label toolbar cut off PD-1238

- packages/graphing/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/graphing/configure/src/__tests__/__snapshots__/graphing-config.test.js.snap
- packages/graphing/configure/src/configure.jsx
- packages/graphing/configure/src/correct-response.jsx
- packages/graphing/configure/src/defaults.js
- packages/graphing/configure/src/graphing-config.jsx
- packages/graphing/controller/src/defaults.js
- packages/graphing/docs/config-schema.json
- packages/graphing/docs/config-schema.json.md
- packages/graphing/docs/demo/generate.js
- packages/graphing/docs/pie-schema.json
- packages/graphing/docs/pie-schema.json.md
- packages/graphing/src/main.jsx
- packages/pie-models/src/pie/graphing/index.ts
BREAKING CHANGE: Added coordinatesOnHover property to the model
https://illuminate.atlassian.net/browse/PD-188
> feat(graphing): Displayed point coordinates on hover PD-188

- packages/match/configure/src/answer-config-block.jsx
- packages/match/configure/src/configure.jsx
- packages/match/configure/src/defaults.js
- packages/match/configure/src/row.jsx
- packages/match/docs/demo/generate.js
- packages/match/docs/pie-schema.json
- packages/match/docs/pie-schema.json.md
- packages/pie-models/src/pie/match/index.ts
> feat(match) : added option for changing editor toolbar's position

- packages/number-line/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/number-line/configure/src/defaults.js
- packages/number-line/configure/src/main.jsx
- packages/number-line/docs/demo/generate.js
- packages/number-line/docs/pie-schema.json
- packages/number-line/docs/pie-schema.json.md
- packages/pie-models/src/pie/number-line/index.ts
> Feat(number line)/toolbar editor position

- packages/extended-text-entry/configure/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/configure/src/defaults.js
- packages/extended-text-entry/configure/src/main.jsx
- packages/extended-text-entry/controller/src/defaults.js
- packages/extended-text-entry/docs/demo/generate.js
- packages/extended-text-entry/docs/pie-schema.json
- packages/extended-text-entry/docs/pie-schema.json.md
- packages/pie-models/src/pie/extended-text-entry/index.ts
> Feat(extended text entry)/toolbar editor position

- packages/hotspot/configure/src/defaults.js
- packages/hotspot/configure/src/root.jsx
- packages/hotspot/docs/demo/generate.js
- packages/hotspot/docs/pie-schema.json
- packages/hotspot/docs/pie-schema.json.md
- packages/pie-models/src/pie/hotspot/index.ts
> feat(hotspot): Added option to set toolbar editor position

- packages/pie-models/src/pie/placement-ordering/index.ts
- packages/placement-ordering/configure/src/__tests__/__snapshots__/design.test.jsx.snap
- packages/placement-ordering/configure/src/choice-editor.jsx
- packages/placement-ordering/configure/src/choice-tile.jsx
- packages/placement-ordering/configure/src/defaults.js
- packages/placement-ordering/configure/src/design.jsx
- packages/placement-ordering/docs/demo/generate.js
- packages/placement-ordering/docs/pie-schema.json
- packages/placement-ordering/docs/pie-schema.json.md
> feat(placement-ordering): added option to set toolbar editor position

- packages/image-cloze-association/controller/src/utils.js
https://illuminate.atlassian.net/browse/PD-1249
> fix(image-cloze-association): Fixed scoring method console errors PD-1249

- packages/image-cloze-association/src/root.jsx
- packages/image-cloze-association/src/utils-correctness.js
https://illuminate.atlassian.net/browse/PD-1246
> fix(image-cloze-association): Added missing responses and marked as incorrect in evaluate mode PD-1246

- packages/math-inline/src/main.jsx
My fix is applied for Safari only. **onblur** doesn't work as expected for some elements. Please see [this](https://stackoverflow.com/a/42764495/5757635) also. 
Reported [here](https://illuminate.atlassian.net/browse/CTT-174).
Any suggestion is welcome.
> fix(CTT-174): add safari tooltip fix

- packages/image-cloze-association/src/__tests__/__snapshots__/root.test.jsx.snap
- packages/image-cloze-association/src/root.jsx
https://illuminate.atlassian.net/browse/PD-1245
> fix(image-cloze-association): add show correct answer toggle for evaluate PD-1245

- packages/multiple-choice/configure/src/defaults.js
- packages/multiple-choice/configure/src/main.jsx
- packages/multiple-choice/controller/src/defaults.js
- packages/multiple-choice/controller/src/index.js
- packages/multiple-choice/controller/src/utils.js
- packages/multiple-choice/docs/demo/generate.js
- packages/multiple-choice/src/choice-input.jsx
- packages/pie-models/src/pie/multiple-choice/index.ts
Added option to set accessibility label -> If enabled and author enter a value it will be displayed as a aria-label attribute;
If is enabled but the author didn't enter a value the aria-label attribute will have the choice label value.
> Feat(multiple choice)/accessibility label

- packages/math-inline/controller/src/index.js
- packages/math-inline/package.json
- yarn.lock
-add math validation package in  math-inline package.json and use it at evaluate
> feat/add-math -validation-pkg

- packages/hotspot/configure/src/hotspot-drawable.jsx
https://illuminate.atlassian.net/browse/PD-261
> fix(hotspot): Added a max width when loading a new image PD-261

- packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-1263
> fix(math-inline): Added a min width for line notation PD-1263

- packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-1274
> fix(math-inline): Removed the margin top of the response area PD-1274

- packages/ebsr/configure/src/index.js
- packages/ebsr/configure/src/main.jsx
- packages/ebsr/controller/src/index.js
- packages/multiple-choice/configure/src/__tests__/root.test.jsx
- packages/multiple-choice/configure/src/index.js
- packages/multiple-choice/configure/src/main.jsx
- packages/multiple-choice/controller/src/__tests__/index.test.js
- packages/multiple-choice/controller/src/index.js
@andreeimiron I closed https://github.com/pie-framework/pie-elements/pull/676 because it seems we made unnecessary updates on the versions.
I cherry-picked the code and recreated the PR.
Can you please check we have everything we need in this PR and also re-test the changes on this branch?
Thank you.
> chore(ebsr): Support old models (user verticalMode if choicesLayout is not set)

- packages/math-inline/src/__tests__/main.test.js
- packages/math-inline/src/main.jsx
**NEED TO MERGE https://github.com/pie-framework/pie-lib/pull/343 FIRST**
> fix(math-inline): render parallel sign with bigger font-size PD-1258

- packages/math-inline/package.json
- yarn.lock
> chore: Revert @pie-lib/math-input version update because tests are failing

- packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-1281
> fix(math-inline): fix based log button PD-1281

- packages/explicit-constructed-response/package.json
- packages/explicit-constructed-response/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/explicit-constructed-response/src/main.js
- packages/explicit-constructed-response/src/print.js
- yarn.lock
**_Instructor view:_** 
**_Student view_**
> feat(explicit-constructed-response): implement print PD-1284

- packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-1264
> fix(math-inline): Fixed arrows for pits

- packages/hotspot/configure/src/__tests__/__snapshots__/hotspot-container.test.js.snap
- packages/hotspot/configure/src/hotspot-container.jsx
https://illuminate.atlassian.net/browse/PD-478
> feat(hotspot): add the possibility to paste image in authoring PD-478

- packages/match/src/index.js
https://illuminate.atlassian.net/browse/PD-902
> fix(match): Fixed the session for pits PD-902

- packages/math-inline/configure/src/response.jsx
https://illuminate.atlassian.net/browse/PD-333
> fix(math-inline): show add alternate button for both literal and symbolic validation PD-333

- packages/categorize/configure/src/design/categories/choice-preview.jsx
- packages/categorize/configure/src/design/categories/droppable-placeholder.jsx
Fixed Recorder bug and props warning
https://user-images.githubusercontent.com/56835388/133999272-fcde236d-24ab-4b35-958f-5c1f2320d669.mov
https://user-images.githubusercontent.com/56835388/133999313-a59fcbf4-1027-4138-8115-4e773da6fdb8.mov
> fix(categorize): delete choice from alternate respose too when choice is deleted from choices

- packages/rubric/src/main.jsx
https://illuminate.atlassian.net/browse/PD-1313
> feat(rubric): Added Studio support: Treat 'null' as null value for sample answer PD-1313

- packages/math-inline/configure/src/general-config-block.jsx
https://illuminate.atlassian.net/browse/PD-1305
> fix(math-inline): do not hide math editor when focus is still on response template PD-1305

- packages/multiple-choice/src/choice-input.jsx
- packages/multiple-choice/src/choice.jsx
https://illuminate.atlassian.net/browse/CTT-134
> fix: show tick if available only in evaluate mode

- packages/math-inline/controller/src/index.js
- packages/math-inline/src/main.jsx
- packages/math-inline/src/simple-question-block.jsx
https://illuminate.atlassian.net/browse/PD-994
> fix(math-inline): Evaluate should not highlight answers when no correct response is defined + refactoring PD-994

- packages/math-inline/controller/package.json
> chore: bump math-validation version

- packages/match/configure/src/row.jsx
https://illuminate.atlassian.net/browse/PD-1335
> feat(match): remove list buttons from question text PD-1335

- packages/placement-ordering/configure/src/choice-tile.jsx
https://illuminate.atlassian.net/browse/PD-1337
> feat(placement-ordering): remove list buttons from choice labels PD-1337

- packages/placement-ordering/configure/package.json
- packages/placement-ordering/configure/src/__tests__/__snapshots__/design.test.jsx.snap
- packages/placement-ordering/configure/src/choice-editor.jsx
- packages/placement-ordering/configure/src/design.jsx
- yarn.lock
https://illuminate.atlassian.net/browse/PD-1330
https://illuminate.atlassian.net/browse/PD-1342
https://user-images.githubusercontent.com/61793308/138287973-5f89ea29-3d0c-4112-9593-28c294fbb2a4.mov
> feat(placement-ordering): add shuffle button to UI for authoring PD-1300. Use choices label value in authoring PD-1342

- packages/match/configure/src/defaults.js
https://illuminate.atlassian.net/browse/PD-1333
> fix(match): set default false for lock choice order settings PD-1333

- packages/placement-ordering/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1349
> fix(placement-ordering): fix create correct session for IBX browse items PD-1349

- packages/placement-ordering/configure/src/choice-editor.jsx
https://illuminate.atlassian.net/browse/PD-1329
https://user-images.githubusercontent.com/61793308/138260747-a4d0d202-4b3e-4cef-bf41-7da1d40d34a2.mov
> fix(placement-ordering): fix issues with dragging answer choices in authoring PD-1329

- packages/match/configure/src/__tests__/configure.test.js
- packages/match/configure/src/answer-config-block.jsx
https://illuminate.atlassian.net/browse/PD-1336
> feat(match): change drag-and-drop behavior from swap to push PD-1336

- packages/explicit-constructed-response/src/__tests__/main.test.jsx
- packages/explicit-constructed-response/src/main.js
https://illuminate.atlassian.net/browse/PD-1353
> fix(explicit-constructed-response): call session change depending on input max length PD-1353

- packages/rubric/src/__tests__/__snapshots__/rubric-view.test.jsx.snap
- packages/rubric/src/main.jsx
- packages/select-text/docs/demo/generate.js
use "1 PT" instead of "1 PTS": https://illuminate.atlassian.net/browse/PD-1374
width issue in IBX: https://illuminate.atlassian.net/browse/PD-1373
> fix(rubric): use singular 1PT instead of 1PTS, fix style in IBX PD-1373, PD-1374

- packages/charting/src/main.jsx
https://illuminate.atlassian.net/browse/PD-1362
> fix(charting): improve styling for PRB PD-1362

- packages/drag-in-the-blank/src/main.js
- packages/inline-dropdown/src/__tests__/__snapshots__/inline-dropdown.test.jsx.snap
- packages/inline-dropdown/src/inline-dropdown.jsx
https://illuminate.atlassian.net/browse/PD-1379
> feat(drag-in-the-blank, inline-dropdown): move rationale after the item content PD-1379

- packages/math-inline/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/math-inline/configure/src/defaults.js
- packages/math-inline/configure/src/general-config-block.jsx
- packages/math-inline/controller/src/defaults.js
https://illuminate.atlassian.net/browse/PD-1385
> fix(math-inline): default editors to grade 8-HS PD-1385

- packages/match/src/__tests__/answer-grid.test.js
- packages/match/src/answer-grid.jsx
- packages/match/src/main.jsx
https://illuminate.atlassian.net/browse/PD-1378
https://user-images.githubusercontent.com/61793308/141464126-00f94afa-c06d-4130-b705-4c0eacfe2ecf.mov
> fix(match): indicate answer correctness in evaluate mode PD-1378

- packages/passage/src/stimulus-tabs.jsx
https://illuminate.atlassian.net/browse/PD-1391
> fix(passage): fix audio content for Safari for imported content PD-1391

- packages/drag-in-the-blank/configure/src/__tests__/choices.test.jsx
- packages/drag-in-the-blank/configure/src/choices.jsx
https://illuminate.atlassian.net/browse/PD-1404
https://user-images.githubusercontent.com/61793308/142608184-179999c0-746e-44bf-8156-c7c18ad38915.mov
> fix(drag-in-the-blank): fix validation behavior PD-1404

- packages/categorize/src/categorize/choices.jsx
choicesLabel was not rendered correctly, it's rendered as text instead of html
> fix(categorize): render choicesLabel as Html

- packages/categorize/src/__tests__/__snapshots__/index.test.js.snap
- packages/categorize/src/categorize/__tests__/__snapshots__/index.test.jsx.snap
- packages/categorize/src/categorize/choice.jsx
- packages/categorize/src/categorize/index.jsx
https://illuminate.atlassian.net/browse/PD-1420
> fix(categorize): fix layout issue and choice content direction PD-1420

- packages/multiple-choice/src/choice-input.jsx
https://illuminate.atlassian.net/browse/PD-1433
> fix(multiple-choice): fix colors for evaluate and view PD-1433

- packages/extended-text-entry/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/src/main.jsx
https://illuminate.atlassian.net/browse/DNA-13102?focusedCommentId=866230&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-866230
> fix(extended-text-entry): add static classname for editor DNA-13102

- packages/number-line/controller/src/defaults.js
- packages/number-line/docs/demo/generate.js
- yarn.lock
Removed props: snapPerTick, showMinorTicks, tickFrequency
> chore(number-line): remove not implemented props from model

- packages/charting/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1480
> fix(charting): view mode should not show correctness PD-1480

- packages/number-line/configure/src/index.js
- packages/number-line/controller/src/index.js
- packages/number-line/docs/demo/generate.js
- packages/number-line/docs/pie-schema.json
- packages/number-line/docs/pie-schema.json.md
- packages/number-line/src/number-line/graph/index.jsx
- packages/number-line/src/number-line/graph/tick-utils.js
- packages/number-line/src/number-line/graph/ticks.jsx
- packages/number-line/src/number-line/index.jsx
- packages/pie-models/src/pie/number-line/index.ts
https://illuminate.atlassian.net/browse/PD-472
> feat(number-line): Added support for fractions PD-472

- packages/graphing/configure/src/index.js
https://illuminate.atlassian.net/browse/PD-1500
> fix(graphing): no correctness indicator if correct response is authored PD-1500

- packages/explicit-constructed-response/configure/src/markupUtils.js
https://illuminate.atlassian.net/browse/PD-1507
> fix(explicit-constructed-response): Displayed delta, theta, times and tan symbols correctly PD-1507

- packages/drag-in-the-blank/configure/src/markupUtils.js
- packages/explicit-constructed-response/configure/src/markupUtils.js
- packages/inline-dropdown/configure/src/markupUtils.js
https://illuminate.atlassian.net/browse/PD-1535
> fix(explcit-constructed-response, inline-dropdown, drag-in-the-blank): Fixed some math symbols rendering PD-1535

- packages/drag-in-the-blank/configure/src/choices.jsx
https://illuminate.atlassian.net/browse/PD-1568
> fix(drag-in-the-blank): Fixed choices with math content marked as duplicated on edit PD-1568

- packages/select-text/package.json
- packages/select-text/src/main.jsx
- packages/select-text/src/print.js
https://illuminate.atlassian.net/browse/PD-1526
> feat(select-text): implement print PD-1526

- packages/extended-text-entry/src/annotation/annotation-editor.jsx
https://illuminate.atlassian.net/browse/PD-1583
> fix(extended-text-entry): Fixed multi-lines annotation that gets single-spaced PD-1583

- packages/extended-text-entry/src/annotation/__tests__/__snapshots__/annotation-editor.test.jsx.snap
- packages/extended-text-entry/src/annotation/annotation-editor.jsx
https://illuminate.atlassian.net/browse/PD-1587
> fix(extended-text-entry): Tighten up the right spacing PD-1587

- packages/math-inline/src/print.js
https://illuminate.atlassian.net/browse/PD-1622
> fix(math-inline): print - set expression in model PD-1622

- packages/multiple-choice/src/print.js
https://illuminate.atlassian.net/browse/PD-1623
> fix(multiple-choice): set choices layout for print PD-1623

- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/alternateSection.test.jsx.snap
- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/ecr-toolbar.test.jsx.snap
- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/explicit-constructed-response/configure/src/alternateSection.jsx
- packages/explicit-constructed-response/configure/src/ecr-toolbar.jsx
- packages/explicit-constructed-response/configure/src/main.jsx
feat(choices): made sure adding a choice changes the markup [PD-1592]
https://illuminate.atlassian.net/browse/PD-1592
> feat(choices): made sure adding a choice changes the markup [PD-1592]

- packages/hotspot/src/hotspot/container.jsx
- packages/hotspot/src/hotspot/index.jsx
- packages/hotspot/src/hotspot/polygon.jsx
- packages/hotspot/src/hotspot/rectangle.jsx
https://illuminate.atlassian.net/browse/PD-360
I will have to take care of drawing response also. Same issue happens there. 
I guess that will be another ticket - there will be more work than it is in this PR, wdyt @andreeapescar?
> fix(hotspot): add support for --pie-zoom css property PD-360

- packages/extended-text-entry/src/annotation/annotation-editor.jsx
https://illuminate.atlassian.net/browse/PD-1583
> fix(extended-text-entry): Removed line-height that caused multi-lines annotation to get single-spaced PD-1583

- packages/drawing-response/src/drawing-response/__tests__/__snapshots__/container.test.jsx.snap
- packages/drawing-response/src/drawing-response/__tests__/__snapshots__/drawing-main.test.jsx.snap
- packages/drawing-response/src/drawing-response/__tests__/container.test.jsx
- packages/drawing-response/src/drawing-response/__tests__/drawing-main.test.jsx
- packages/drawing-response/src/drawing-response/container.jsx
- packages/drawing-response/src/drawing-response/drawable-image.jsx
- packages/drawing-response/src/drawing-response/drawable-main.jsx
- packages/drawing-response/src/drawing-response/drawable-text.jsx
https://illuminate.atlassian.net/browse/PD-1628
> fix(drawing-response): add support for --pie-zoom css property PD-1628

- packages/drawing-response/configure/src/root.jsx
https://illuminate.atlassian.net/browse/PD-1636
> fix(drawing-response): Added image support for item stem PD-1636

- packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-1641
> fix(math-inline): PD-1641 move note in tooltip in evaluate mode

- packages/drawing-response/configure/src/__tests__/__snapshots__/root.test.jsx.snap
- packages/drawing-response/configure/src/defaults.js
- packages/drawing-response/configure/src/index.js
- packages/drawing-response/configure/src/root.jsx
- packages/drawing-response/controller/src/__tests__/index.test.js
- packages/drawing-response/controller/src/index.js
- packages/drawing-response/docs/config-schema.json
- packages/drawing-response/docs/config-schema.json.md
- packages/drawing-response/docs/demo/generate.js
- packages/drawing-response/docs/pie-schema.json
- packages/drawing-response/docs/pie-schema.json.md
- packages/drawing-response/src/drawing-response/container.jsx
- packages/drawing-response/src/drawing-response/drawable-main.jsx
- packages/drawing-response/src/drawing-response/index.jsx
- packages/pie-models/src/pie/drawing-response/index.ts
https://illuminate.atlassian.net/browse/PD-1642
> fix(drawing-response): PD-1642 fix background image property 

- packages/drawing-response/src/drawing-response/drawable-main.jsx
[PD-1664](https://illuminate.atlassian.net/browse/PD-1664)
> fix(drawing-response): calculate image scaled if image dimensions exists only 

- packages/ebsr/src/print.js
https://illuminate.atlassian.net/browse/PD-1665
> fix(ebsr-print): PD-1665 fix correctness color not being shown

- packages/extended-text-entry/src/main.jsx
https://illuminate.atlassian.net/browse/PD-1660
> fix(extended-text-entry): PD-1660 fix dom nesting warning

- packages/multiple-choice/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1202
> feat: multiple-choice validation

- packages/categorize/src/index.js
- packages/charting/src/index.js
- packages/drag-in-the-blank/src/index.js
- packages/drawing-response/src/index.js
- packages/ebsr/src/index.js
- packages/explicit-constructed-response/src/index.js
- packages/extended-text-entry/src/index.js
- packages/graphing/src/index.js
- packages/hotspot/src/index.js
- packages/image-cloze-association/src/index.js
- packages/inline-dropdown/src/index.js
- packages/likert/src/index.js
- packages/match-list/src/index.js
- packages/match/src/index.js
- packages/math-inline/src/index.js
- packages/matrix/src/index.js
- packages/multi-trait-rubric/src/index.js
- packages/multiple-choice/src/index.js
- packages/number-line/src/index.js
- packages/placement-ordering/src/index.js
- packages/rubric/src/index.js
- packages/select-text/src/index.js
https://illuminate.atlassian.net/browse/PD-1668
> fix: added getters for the session PD-1668

- packages/hotspot/configure/src/hotspot-drawable.jsx
https://illuminate.atlassian.net/browse/PD-1674
> (hotspot): add sanity check for box

- packages/hotspot/configure/src/root.jsx
- packages/hotspot/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1702
> feat(hotspot): added configurable validation PD-1702

- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/alternateSection.test.jsx.snap
- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/explicit-constructed-response/configure/src/alternateResponses.jsx
- packages/explicit-constructed-response/configure/src/alternateSection.jsx
- packages/explicit-constructed-response/configure/src/ecr-toolbar.jsx
- packages/explicit-constructed-response/configure/src/index.js
- packages/explicit-constructed-response/configure/src/main.jsx
- packages/explicit-constructed-response/configure/src/utils.js
- packages/explicit-constructed-response/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1706
> feat(explicit-constructed-response): added configurable validation PD-1706

- packages/math-inline/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/math-inline/configure/src/general-config-block.jsx
- packages/math-inline/configure/src/response.jsx
- packages/math-inline/configure/src/utils.js
- packages/math-inline/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1704
> feat(math-inline): added configurable validation PD-1704

- packages/drag-in-the-blank/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/drag-in-the-blank/configure/src/choices.jsx
- packages/drag-in-the-blank/configure/src/main.jsx
- packages/drag-in-the-blank/configure/utils.js
- packages/drag-in-the-blank/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1708
> feat(drag-in-the-blank): added configurable validation PD-1708

- packages/categorize/configure/src/design/__tests__/__snapshots__/header.test.jsx.snap
- packages/categorize/configure/src/design/buttons.jsx
- packages/categorize/configure/src/design/categories/__tests__/__snapshots__/index.test.jsx.snap
- packages/categorize/configure/src/design/categories/index.jsx
- packages/categorize/configure/src/design/choices/choice.jsx
- packages/categorize/configure/src/design/choices/index.jsx
- packages/categorize/configure/src/design/header.jsx
- packages/categorize/configure/src/design/index.jsx
- packages/categorize/configure/src/design/input-header.jsx
- packages/categorize/configure/src/utils.js
- packages/categorize/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1739
> feat(categorize): added configurable validation PD-1739

- packages/match/configure/src/answer-config-block.jsx
- packages/match/configure/src/general-config-block.jsx
- packages/match/configure/src/row.jsx
- packages/match/configure/utils.js
- packages/match/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1710
> feat(match): added validation PD-1710

- packages/placement-ordering/configure/src/__tests__/__snapshots__/design.test.jsx.snap
- packages/placement-ordering/configure/src/design.jsx
- packages/placement-ordering/configure/src/utils.js
- packages/placement-ordering/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1743
> feat(placement-ordering): added validation PD-1743

- packages/select-text/configure/src/__tests__/__snapshots__/design.test.jsx.snap
- packages/select-text/configure/src/design.jsx
No ticket - changed info tooltip position for consistency between item types
> feat(select-text): ui/ux for item validation - fix info tooltip

- packages/number-line/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/number-line/configure/src/card-bar.jsx
- packages/number-line/configure/src/main.jsx
- packages/number-line/configure/src/utils.js
- packages/number-line/controller/src/index.js
This is marked as draft since there will need to be validation ui/ux implemented
https://illuminate.atlassian.net/browse/PD-1747
> feat(number-line): item validation PD-1747 & PD-1748

- packages/drawing-response/src/drawing-response/__tests__/__snapshots__/drawing-main.test.jsx.snap
- packages/drawing-response/src/drawing-response/drawable-main.jsx
- packages/drawing-response/src/drawing-response/drawable-text.jsx
https://illuminate.atlassian.net/browse/PD-1633
> feat: Touch screen support for Drawing Response PD-1633

- packages/graphing/configure/src/__tests__/__snapshots__/correct-response.test.js.snap
- packages/graphing/configure/src/correct-response.jsx
https://illuminate.atlassian.net/browse/PD-1606
> feat(graphing): Added delete button for alternates + UI improvements PD-1606

- packages/number-line/configure/src/main.jsx
this PR is made to base 'Master'
> remove console.log from number-line

- packages/ebsr/configure/src/__tests__/index.test.js
- packages/ebsr/configure/src/main.jsx
- packages/ebsr/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1799
> feat(ebsr): implement item validation PD-1799

- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/explicit-constructed-response/configure/src/utils.js
https://illuminate.atlassian.net/browse/PD-1819
> fix(explicit-constructed-response): change validation message

- packages/charting/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1365
> fix(charting): keep chart interactive in IBX preview mode PD-1365

- packages/extended-text-entry/configure/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/configure/src/defaults.js
- packages/extended-text-entry/configure/src/main.jsx
- packages/extended-text-entry/controller/src/index.js
- packages/extended-text-entry/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/src/main.jsx
- packages/pie-models/src/pie/extended-text-entry/index.ts
https://illuminate.atlassian.net/browse/PD-1461
https://illuminate.atlassian.net/browse/PD-1462
> feat(input): added configurability for inserting spanish and special characters [PD-1461], [PD-1462]

- packages/match/configure/src/answer-config-block.jsx
- packages/match/configure/src/configure.jsx
- packages/match/configure/src/defaults.js
- packages/match/configure/src/row.jsx
- packages/match/docs/config-schema.json
- packages/match/docs/config-schema.json.md
- packages/match/docs/pie-schema.json
- packages/match/docs/pie-schema.json.md
- packages/pie-models/src/pie/match/index.ts
> feat(match): add maxImageWidth and maxImageHeight props PD-1801

- packages/pie-models/src/pie/select-text/index.ts
- packages/select-text/configure/src/__tests__/__snapshots__/design.test.jsx.snap
- packages/select-text/configure/src/defaultConfiguration.js
- packages/select-text/configure/src/design.jsx
- packages/select-text/docs/config-schema.json
- packages/select-text/docs/config-schema.json.md
- packages/select-text/docs/pie-schema.json
- packages/select-text/docs/pie-schema.json.md
> feat(select-text): add maxImageWidth and maxImageHeight props PD-1801

- packages/math-inline/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/math-inline/configure/src/configure.jsx
- packages/math-inline/configure/src/defaults.js
- packages/math-inline/configure/src/general-config-block.jsx
- packages/math-inline/docs/config-schema.json
- packages/math-inline/docs/config-schema.json.md
- packages/math-inline/docs/pie-schema.json
- packages/math-inline/docs/pie-schema.json.md
- packages/pie-models/src/pie/math-inline/index.ts
> feat(math-inline): add maxImageWidth and maxImageHeight props PD-1801

- packages/charting/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/charting/configure/src/configure.jsx
- packages/charting/configure/src/defaults.js
- packages/charting/docs/config-schema.json
- packages/charting/docs/config-schema.json.md
- packages/charting/docs/pie-schema.json
- packages/charting/docs/pie-schema.json.md
- packages/pie-models/src/pie/charting/index.ts
> feat(charting): add maxImageWidth and maxImageHeight props PD-1801

- packages/graphing/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/graphing/configure/src/configure.jsx
- packages/graphing/configure/src/defaults.js
- packages/graphing/docs/config-schema.json
- packages/graphing/docs/config-schema.json.md
- packages/graphing/docs/pie-schema.json
- packages/graphing/docs/pie-schema.json.md
- packages/pie-models/src/pie/graphing/index.ts
> feat(graphing): add maxImageWidth and maxImageHeight props PD-1801

- packages/ebsr/configure/src/defaults.js
- packages/ebsr/docs/config-schema.json
- packages/ebsr/docs/config-schema.json.md
- packages/ebsr/docs/pie-schema.json
- packages/ebsr/docs/pie-schema.json.md
- packages/pie-models/src/pie/ebsr/index.ts
> feat(ebsr): add maxImageWidth and maxImageHeight props PD-1801

- packages/drag-in-the-blank/controller/src/index.js
- packages/inline-dropdown/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1848
> fix: inline-dropdown and drag-in-the-blank fix validation error PD-1848

- packages/graphing/configure/src/__tests__/__snapshots__/graphing-config.test.js.snap
- packages/graphing/configure/src/graphing-config.jsx
https://illuminate.atlassian.net/browse/PD-1693
> feat(graphing): put background shapes tools into a collapsible pannel PD-1693

- packages/ebsr/src/index.js
- packages/ebsr/src/print.js
- packages/hotspot/configure/src/hotspot-container.jsx
Fixes various sentry issues.
[PD-1893](https://illuminate.atlassian.net/browse/PD-1893)
> fix(hotpost): sentry

- packages/graphing/configure/src/correct-response.jsx
https://illuminate.atlassian.net/browse/PD-1607
> feat(graphing): enabled drag and drop sorting for toolbar tools PD-1607

- packages/math-inline/configure/package.json
- packages/math-inline/package.json
- yarn.lock
https://illuminate.atlassian.net/browse/PD-1893
> fix: bump mathquill to 1.1.3

- packages/math-inline/configure/src/general-config-block.jsx
https://illuminate.atlassian.net/browse/PD-1897
> fix(math-inline): fix validation message tooltip style PD-1897

- packages/charting/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/charting/configure/src/charting-config.jsx
- packages/charting/configure/src/configure.jsx
- packages/charting/configure/src/correct-response.jsx
https://illuminate.atlassian.net/browse/PD-1727
> feat(charting): update labels, UI text and style PD-1727

- packages/charting/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/charting/configure/src/charting-config.jsx
- packages/charting/configure/src/configure.jsx
- packages/charting/configure/src/defaults.js
https://illuminate.atlassian.net/browse/PD-1731
> feat(charting): add size constraints, configure acces for the client systems to control width and height visibility and constraints PD-1731

- packages/charting/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/charting/configure/src/charting-config.jsx
- packages/charting/configure/src/correct-response.jsx
https://illuminate.atlassian.net/browse/PD-1724
> feat(charting): remove added categories from correctReponse if addCategoryEnabled is false -PD-1724-a

- packages/graphing/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/graphing/configure/src/__tests__/__snapshots__/graphing-config.test.js.snap
- packages/graphing/configure/src/configure.jsx
- packages/graphing/configure/src/defaults.js
- packages/graphing/configure/src/graphing-config.jsx
- packages/graphing/docs/config-schema.json
- packages/graphing/docs/config-schema.json.md
- packages/graphing/docs/pie-schema.json
- packages/graphing/docs/pie-schema.json.md
- packages/pie-models/src/pie/graphing/index.ts
https://illuminate.atlassian.net/browse/PD-1719
> feat(graphing): added pixel grid lines support PD-1719

- packages/drawing-response/configure/src/image-container.jsx
https://illuminate.atlassian.net/browse/PD-1933
> fix(drawing-response): fix svg not loading PD-1933

- packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-1844
> fix(math-inline) PD-1844: Unwanted screen artifact in some MER items

- packages/math-inline/configure/src/general-config-block.jsx
https://illuminate.atlassian.net/browse/PD-1521.
> feat(math-inline): Overwrite mathquill font

- packages/charting/configure/src/correct-response.jsx
https://illuminate.atlassian.net/browse/PD-1969
> fix(charting): update correct response data correctly when range is changed from panel config PD-1969

- packages/charting/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/charting/configure/src/charting-config.jsx
- packages/charting/configure/src/configure.jsx
https://illuminate.atlassian.net/browse/PD-1732
> feat(charting): add pixel guides for Chart 1 PD-1732

- packages/charting/configure/src/charting-config.jsx
- packages/charting/configure/src/correct-response.jsx
https://illuminate.atlassian.net/browse/PD-1724
> fix(charting): remove categories added in Chart 2,  after user confirmation, when user sets addCategoryEnabled to false PD-1724

- packages/number-line/configure/src/index.js
- packages/number-line/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1648
> fix(number-line): adjust domain min and max values PD-1648

- packages/drag-in-the-blank/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-2054
> fix(drag-in-the-blank): changed the validation error message PD-2054

- packages/graphing/configure/package.json
- packages/graphing/configure/src/index.js
https://illuminate.atlassian.net/browse/PD-2082
> fix: render math content in configure part PD-2082

- packages/multiple-choice/configure/src/main.jsx
https://illuminate.atlassian.net/browse/PD-23
> fix(multiple-choice): add upload file option in choices PD-23

- packages/math-inline/configure/src/response.jsx
https://illuminate.atlassian.net/browse/PD-2055
> fix(math-inline): fix validation ui for alternate responses PD-2055

- packages/number-line/src/number-line/graph/elements/__tests__/point.test.jsx
- packages/number-line/src/number-line/graph/elements/point.jsx
https://illuminate.atlassian.net/browse/PD-1948
> fix(number-line): increase draggable zone for number-line point, for better user experience on ipad

- packages/placement-ordering/configure/src/__tests__/__snapshots__/design.test.jsx.snap
- packages/placement-ordering/configure/src/design.jsx
https://illuminate.atlassian.net/browse/PD-2153
https://illuminate.atlassian.net/browse/PD-2154
> fix: placement-ordering PD-2153 PD-2154

- packages/math-inline/configure/src/configure.jsx
https://illuminate.atlassian.net/browse/PD-2171
> fix(math-inline): add sanity checks for withRubric PD-2171

- packages/select-text/configure/src/design.jsx
https://illuminate.atlassian.net/browse/PD-2172
> fix(select-text): add sanity checks for withRubric PD-2172

- packages/hotspot/configure/src/defaults.js
- packages/hotspot/configure/src/root.jsx
https://illuminate.atlassian.net/browse/PD-2173
> fix(hotspot): add sanity checks for withRubric PD-2173

- packages/drawing-response/configure/src/root.jsx
https://illuminate.atlassian.net/browse/PD-2174
> fix(drawing-response): add sanity checks for withRubric PD-2174

- packages/placement-ordering/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-2156
> fix(placement-ordering): fix feedback behavior PD-2156

- packages/placement-ordering/configure/src/__tests__/__snapshots__/design.test.jsx.snap
- packages/placement-ordering/configure/src/choice-editor.jsx
- packages/placement-ordering/configure/src/choice-tile.jsx
- packages/placement-ordering/configure/src/design.jsx
https://illuminate.atlassian.net/browse/PD-2162
> feat(placement-ordering): add a new label and change choices one PD-2162

- packages/placement-ordering/configure/src/choice-tile.jsx
https://illuminate.atlassian.net/browse/PD-2170
> fix(placement-ordering): move the delete choice button PD-2170

- packages/graphing/configure/src/configure.jsx
- packages/graphing/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1746
> fix(graphing): validation PD-1746

- packages/drag-in-the-blank/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/drag-in-the-blank/configure/src/defaults.js
- packages/drag-in-the-blank/configure/utils.js
https://illuminate.atlassian.net/browse/PD-2413
> fix(drag-in-the-blank): added config deafults for minChoices PD-2413

- packages/graphing/configure/src/__tests__/__snapshots__/graphing-config.test.js.snap
- packages/graphing/configure/src/graphing-config.jsx
- packages/graphing/configure/src/utils.js
https://illuminate.atlassian.net/browse/PD-1687
> feat(graphing): added support for ungraphable objects

- packages/extended-text-entry/configure/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/configure/src/defaults.js
https://illuminate.atlassian.net/browse/PD-1993
> fix(extended-text-entry): update default label for player's spellcheck property in settings panel PD-1993

- packages/match-list/src/__tests__/__snapshots__/main.test.js.snap
- packages/match-list/src/answer.js
- packages/match-list/src/choices-list.jsx
- packages/match-list/src/main.jsx
https://illuminate.atlassian.net/browse/PD-1956
> fix(match-list): add onRemoveAnswer property in the droppable-placeholder and get the promptId on drag PD-1956

- packages/ebsr/configure/src/defaults.js
- packages/ebsr/configure/src/index.js
- packages/ebsr/configure/src/main.jsx
- packages/ebsr/docs/config-schema.json
- packages/ebsr/docs/config-schema.json.md
- packages/ebsr/docs/pie-schema.json
- packages/ebsr/docs/pie-schema.json.md
- packages/pie-models/src/pie/ebsr/index.ts
https://illuminate.atlassian.net/browse/PD-1999
> feat(ebsr): added configuration prop to hide the settings panel PD-1999

- packages/hotspot/configure/src/__tests__/__snapshots__/hotspot-container.test.js.snap
- packages/hotspot/configure/src/__tests__/__snapshots__/root.test.js.snap
- packages/hotspot/configure/src/defaults.js
- packages/hotspot/configure/src/hotspot-container.jsx
- packages/hotspot/configure/src/root.jsx
- packages/hotspot/docs/config-schema.json
- packages/hotspot/docs/config-schema.json.md
- packages/pie-models/src/pie/hotspot/index.ts
https://illuminate.atlassian.net/browse/PD-1999
> feat(hotspot): added configuration prop to hide the settings panel PD-1999

- packages/multi-trait-rubric/configure/src/common.jsx
https://illuminate.atlassian.net/browse/PD-2487
> fix(multi-trait-rubric): set max points dropdown to 1 PD-2487

- packages/complex-rubric/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/complex-rubric/configure/src/main.jsx
https://illuminate.atlassian.net/browse/PD-2492
> fix(complex-rubric): fix rubric type radio buttons PD-2492

- packages/match-list/src/choices-list.jsx
https://illuminate.atlassian.net/browse/PD-2494
> fix(match-list): fix choices arrangement in the drag placeholder PD-2494

- packages/pie-models/src/pie/categorize/index.ts
- packages/pie-models/src/pie/charting/index.ts
- packages/pie-models/src/pie/drag-in-the-blank/index.ts
- packages/pie-models/src/pie/drawing-response/index.ts
- packages/pie-models/src/pie/explicit-constructed-response/index.ts
- packages/pie-models/src/pie/extended-text-entry/index.ts
- packages/pie-models/src/pie/graphing/index.ts
- packages/pie-models/src/pie/hotspot/index.ts
- packages/pie-models/src/pie/image-cloze-association/index.ts
- packages/pie-models/src/pie/inline-dropdown/index.ts
- packages/pie-models/src/pie/match/index.ts
- packages/pie-models/src/pie/math-inline/index.ts
- packages/pie-models/src/pie/multiple-choice/index.ts
- packages/pie-models/src/pie/placement-ordering/index.ts
- packages/pie-models/src/pie/select-text/index.ts
https://illuminate.atlassian.net/browse/PD-2519
> feat: update documentation for withRubric configure prop PD-2519

- packages/multi-trait-rubric/configure/src/main.jsx
https://illuminate.atlassian.net/browse/PD-2467
> fix(multi-trait-rubric): fix scrolling PD-2467

- packages/categorize/src/categorize/categories.jsx
- packages/categorize/src/categorize/index.jsx
https://illuminate.atlassian.net/browse/PD-2513
> fix(categorize): fix style after adding the placeholder for choices PD-2513

- packages/extended-text-entry/src/main.jsx
- packages/multiple-choice/src/main.jsx
https://illuminate.atlassian.net/browse/PD-2476
> feat(multiple-choice): add ARIA attributes PD-2476

- packages/passage/src/stimulus-tabs.jsx
https://illuminate.atlassian.net/browse/PD-2476
> feat(passage): add ARIA attributes PD-2476

- packages/complex-rubric/docs/config-schema.json
- packages/complex-rubric/docs/config-schema.json.md
- packages/complex-rubric/docs/pie-schema.json
- packages/complex-rubric/docs/pie-schema.json.md
- packages/multi-trait-rubric/docs/config-schema.json
- packages/multi-trait-rubric/docs/config-schema.json.md
- packages/pie-models/src/pie/multi-trait-rubric/index.ts
https://illuminate.atlassian.net/browse/PD-2589
> feat(multi-trait-rubric): update documentation PD-2589

- packages/multiple-choice/src/multiple-choice.jsx
https://illuminate.atlassian.net/browse/PD-2440
> feat(multiple-choice): add fieldset and legend tag to radio type choices

- packages/multi-trait-rubric/configure/src/scale.jsx
https://illuminate.atlassian.net/browse/PD-2467
> fix(multi-trait-rubric): show arrow at first maxPoints change PD-2467

- packages/drawing-response/configure/src/index.js
- packages/drawing-response/configure/src/root.jsx
- packages/drawing-response/docs/config-schema.json
- packages/drawing-response/docs/config-schema.json.md
- packages/drawing-response/docs/pie-schema.json
- packages/drawing-response/docs/pie-schema.json.md
- packages/extended-text-entry/configure/src/index.js
- packages/extended-text-entry/configure/src/main.jsx
- packages/extended-text-entry/docs/config-schema.json
- packages/extended-text-entry/docs/config-schema.json.md
- packages/extended-text-entry/docs/pie-schema.json
- packages/extended-text-entry/docs/pie-schema.json.md
- packages/pie-models/src/pie/drawing-response/index.ts
- packages/pie-models/src/pie/extended-text-entry/index.ts
https://illuminate.atlassian.net/browse/PD-2624
> feat: remove force enabled logic from withRubric property PD-2624

- packages/passage/src/index.js
- packages/passage/src/stimulus-tabs.jsx
> fix(passage): add aria-label and role attributes on parent element PD-2476

- packages/multiple-choice/src/index.js
- packages/multiple-choice/src/main.jsx
> feat(multiple-choice):  add aria-label and role attributes on parent element PD-2476

- packages/drawing-response/configure/src/__tests__/index.test.js
- packages/extended-text-entry/configure/src/__tests__/main.test.js
BREAKING CHANGE: create new versions to avoid issues
> fix(drawing-response, extended-text-entry): imports

- packages/match/configure/src/answer-config-block.jsx
- packages/match/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-2655
> fix(match): fix validation bugs PD-2655

- packages/explicit-constructed-response/src/index.js
- packages/extended-text-entry/src/index.js
- packages/inline-dropdown/src/index.js
- packages/math-inline/src/index.js
- extended-text-entry
- inline-dropdown
- explicit-constructed-response
- math-inline
https://illuminate.atlassian.net/browse/PD-2478
> feat: add aria attributes to elements PD-2478

- packages/inline-dropdown/docs/demo/generate.js
https://illuminate.atlassian.net/browse/PD-2633
> fix(inline-dropdown): remove alternateResponse from default model PD-2633

- packages/charting/configure/src/correct-response.jsx
https://illuminate.atlassian.net/browse/PD-2627
> fix(charting): add sanity checks PD-2627

- packages/multiple-choice/src/multiple-choice.jsx
https://illuminate.atlassian.net/browse/PD-2635
> feat(multiple-choice): move the -Show correct answer- toggle after the prompt PD-2635

- packages/hotspot/src/hotspot/index.jsx
https://illuminate.atlassian.net/browse/PD-2640
> feat(hotspot): move the -Show correct answer- toggle after the prompt PD-2640

- packages/ebsr/src/index.js
https://illuminate.atlassian.net/browse/PD-2477
> feat(ebsr): add aria attributes to EBSR element PD-2477

- packages/multiple-choice/src/choice-input.jsx
https://illuminate.atlassian.net/browse/PD-2672
> fix(multiple-choice): fix labels for choices PD-2672

- packages/charting/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/charting/configure/src/correct-response.jsx
https://illuminate.atlassian.net/browse/PD-2675
> fix(charting): fix class error object.object PD-2675

- packages/graphing/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/graphing/configure/src/configure.jsx
https://illuminate.atlassian.net/browse/PD-2671
> fix(graphing): rename settings panel section PD-2671

- packages/ebsr/src/__tests__/index.test.js
- packages/ebsr/src/index.js
https://illuminate.atlassian.net/browse/PD-2477
> fix(ebsr): add aria attributes to ebsr element

- packages/graphing/configure/src/graphing-config.jsx
https://illuminate.atlassian.net/browse/PD-2657
> fix(graphing): discrepancy between configuration and behavior PD-2657

- packages/match/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-2703
> fix(match): fix row errors validation check PD-2703

- packages/multiple-choice/src/choice-input.jsx
https://illuminate.atlassian.net/browse/PD-2699
> fix(multiple-choice): remove aria-label from choices, move choice label in FormControlLabel, add for attribute to choice labels PD-2699

- packages/charting/src/main.jsx
https://illuminate.atlassian.net/browse/PD-2704
> fix(charting): enable horizontal scrolling on the chart PD-2704

- packages/image-cloze-association/controller/src/index.js
- packages/image-cloze-association/src/__tests__/__snapshots__/root.test.jsx.snap
- packages/image-cloze-association/src/root.jsx
https://illuminate.atlassian.net/browse/PD-2708
> fix(image-cloze-association): display rationale PD-2708

- packages/multiple-choice/src/choice-input.jsx
- packages/multiple-choice/src/choice.jsx
https://illuminate.atlassian.net/browse/PD-2447
> fix(multiple-choice): refactor accessibilty attributes for choices PD-2447

- packages/multi-trait-rubric/configure/src/__tests__/__snapshots__/scale.test.jsx.snap
- packages/multi-trait-rubric/configure/src/common.jsx
- packages/multi-trait-rubric/configure/src/scale.jsx
https://illuminate.atlassian.net/browse/PD-2726
> fix(multi-trait-rubric): fix container arrows PD-2726

- packages/math-inline/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1865
> fix(math-inline): enable custom keys in advanced multi PD-1865

- packages/graphing/src/main.jsx
https://illuminate.atlassian.net/browse/PD-576
> fix(graphing): hide student's answer when correct response is displayed PD-576

- packages/match/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-2752
> fix(match): fix validation method PD-2752

- packages/multi-trait-rubric/configure/src/scale.jsx
https://illuminate.atlassian.net/browse/PD-2741
> fix(multi-trait-rubric): fix scrolling issue on add description PD-2741

- packages/match-list/docs/demo/generate.js
- packages/match-list/src/answer.js
https://illuminate.atlassian.net/browse/PD-2768
> fix(match-list): prevent image interaction in choice - this is creating difficulties for drag choices on touch devices PD-2768

- packages/multiple-choice/src/choice-input.jsx
https://illuminate.atlassian.net/browse/PD-2720
> fix(multiple-choice): fix vertical alignment within choice labels PD-2720

- packages/placement-ordering/src/tile.jsx
https://illuminate.atlassian.net/browse/PD-2769
> fix(placement-ordering): prevent image interaction in choice - this is creating difficulties for drag choices on touch devices PD-2769

- packages/image-cloze-association/src/possible-response.jsx
https://illuminate.atlassian.net/browse/PD-2767
> fix(image-cloze-association): preventing the context menu from appearing when long-pressing the image or the choice  on a touch device PD-2767

- packages/charting/configure/src/correct-response.jsx
- packages/charting/docs/demo/generate.js
https://illuminate.atlassian.net/browse/PD-2626
> fix(charting): if correctAnswer is not defined in the model set correctAnswer to equal the data PD-2626

- packages/charting/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/charting/configure/src/charting-config.jsx
- packages/charting/configure/src/configure.jsx
- packages/charting/configure/src/correct-response.jsx
- packages/charting/configure/src/defaults.js
- packages/charting/controller/src/__tests__/index.test.js
- packages/charting/controller/src/index.js
- packages/charting/docs/config-schema.json
- packages/charting/docs/config-schema.json.md
- packages/charting/docs/demo/generate.js
- packages/charting/docs/pie-schema.json
- packages/charting/docs/pie-schema.json.md
- packages/charting/src/main.jsx
- packages/pie-models/src/pie/charting/index.ts
https://illuminate.atlassian.net/browse/PD-2774
> feat(charting): add authoring view settings for authorNewCategoryDefaults and studentNewCategoryDefaultLabel PD-2774

- packages/passage/src/stimulus-tabs.jsx
https://illuminate.atlassian.net/browse/PD-2064
> fix(passage): adjust title color contrast PD-2064

- packages/charting/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/charting/configure/src/configure.jsx
- packages/charting/configure/src/defaults.js
- packages/charting/docs/config-schema.json
- packages/charting/docs/config-schema.json.md
- packages/charting/docs/pie-schema.json
- packages/charting/docs/pie-schema.json.md
- packages/pie-models/src/pie/charting/index.ts
https://illuminate.atlassian.net/browse/PD-2777
> feat(charting): add new authoring view settings to restrict the permitted chart types and allow their names to be changed PD-2777

- packages/hotspot/src/hotspot/container.jsx
https://illuminate.atlassian.net/browse/PD-2075
> fix(hotspot): add a white background for image area PD-2075

- packages/inline-dropdown/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/inline-dropdown/configure/src/inline-dropdown-toolbar.jsx
- packages/inline-dropdown/configure/src/main.jsx
fix: added insert spanish and special characters to the inline-dropdown choices input PD-2128
> fix: added insert spanish and special characters to the inline-dropdown choices input PD-2128

- packages/ebsr/src/index.js
- packages/explicit-constructed-response/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/explicit-constructed-response/src/main.js
- packages/extended-text-entry/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/src/main.jsx
- packages/inline-dropdown/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/inline-dropdown/src/__tests__/__snapshots__/inline-dropdown.test.jsx.snap
- packages/inline-dropdown/src/inline-dropdown.jsx
- packages/math-inline/src/__tests__/__snapshots__/main.test.js.snap
- packages/math-inline/src/main.jsx
- packages/multiple-choice/src/multiple-choice.jsx
https://illuminate.atlassian.net/browse/PD-2883
> feat(multiple-elements): add headings for accessibility PD-2883

- packages/inline-dropdown/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/multiple-choice/src/multiple-choice.jsx
https://illuminate.atlassian.net/browse/PD-2884
> feat(ebsr): make the part labels h3 headings for accessibility PD-2884

- packages/multi-trait-rubric/configure/src/main.jsx
https://illuminate.atlassian.net/browse/PD-2901
> fix(multi-trait-rubric): set 100% width for wide screens PD-2901

- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/alternateSection.test.jsx.snap
- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/ecr-toolbar.test.jsx.snap
- packages/explicit-constructed-response/configure/src/alternateSection.jsx
- packages/explicit-constructed-response/configure/src/ecr-toolbar.jsx
- packages/explicit-constructed-response/configure/src/main.jsx
https://illuminate.atlassian.net/browse/PD-1808
> fix(explicit-constructed-response): ECR authoring: limit length of correct answers when Max Length Per Choice is false

- packages/number-line/configure/src/index.js
https://illuminate.atlassian.net/browse/PD-2795
> feat(number-line): use language from model if it's defined PD-2795

- packages/charting/configure/src/configure.jsx
- packages/charting/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-3121
> fix(charting): refactor validation function to display the validation message a single time for duplicate categories and for empty labels PD-3121

- packages/match/configure/src/row.jsx
https://illuminate.atlassian.net/browse/PD-3231
> fix(match): fix row misalignment by adjusting row content  width PD-3231

- packages/charting/configure/package.json
- packages/charting/configure/src/__tests__/configure.test.js
- packages/charting/configure/src/charting-config.jsx
- packages/charting/configure/src/configure.jsx
- packages/charting/configure/src/correct-response.jsx
- packages/charting/package.json
- packages/charting/src/main.jsx
- yarn.lock
Reverts pie-framework/pie-elements#1540
> Revert "chore: experiment with new lib package"

- packages/charting/controller/src/__tests__/index.test.js
- packages/charting/src/index.js
https://illuminate.atlassian.net/browse/PD-3270
> fix(charting): Add dispatching of ModelSetEvent on model update in charting component, add tests PD-3270

- packages/number-line/configure/src/ticks.jsx
- packages/number-line/src/number-line/graph/__tests__/ticks-utils.test.js
- packages/number-line/src/number-line/graph/index.jsx
- packages/number-line/src/number-line/graph/tick-utils.js
https://illuminate.atlassian.net/browse/PD-1769
> fix(number-line): adjust labels value to be a frequency multiplier PD-1769

- packages/image-cloze-association/src/root.jsx
https://illuminate.atlassian.net/browse/PD-3308
> fix(image-cloze-association): add null checks for responseContainers and possibleResponses PD-3308

- packages/charting/configure/src/correct-response.jsx
https://illuminate.atlassian.net/browse/PD-3164
> fix(charting): fix state sync issues in Define Correct Response Chart when Define Chart data is modified or removed PD-3164

- packages/number-line/configure/src/index.js
https://illuminate.atlassian.net/browse/PD-3361
> fix(number-line): add set method for configuration PD-3361

- packages/number-line/configure/src/defaults.js
- packages/number-line/configure/src/main.jsx
- packages/number-line/configure/src/point-config.jsx
- packages/number-line/configure/src/size.jsx
- packages/number-line/configure/src/ticks.jsx
- packages/number-line/src/number-line/graph/tick-utils.js
- packages/number-line/src/number-line/point-chooser/index.jsx
- packages/number-line/src/number-line/point-chooser/styles.js
1. Added sanity checks for newly added properties in model and configuration.
2. Added comments to function and variables wherever necessary.
> feat(number-line): NLDP item type refactoring SC-27810

- packages/graphing/configure/src/__tests__/__snapshots__/correct-response.test.js.snap
- packages/graphing/configure/src/defaults.js
- packages/graphing/controller/src/defaults.js
- packages/graphing/controller/src/index.js
- packages/graphing/controller/src/utils.js
- packages/graphing/src/utils.js
Added code for absolute value and exponential graph as per below tickets and requirements.
[https://illuminate.atlassian.net/browse/SC-27396](https://illuminate.atlassian.net/browse/SC-27396)
[https://illuminate.atlassian.net/browse/SC-27398](https://illuminate.atlassian.net/browse/SC-27398)
> feat(graphing) Added code for absolute value and exponential graph.

- packages/number-line/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/number-line/configure/src/defaults.js
- packages/number-line/configure/src/main.jsx
https://illuminate.atlassian.net/browse/PD-3368
> fix(number-line): update default value PD-3368

- packages/number-line/configure/src/main.jsx
Fixed issue when NL item is saved and loaded, ticks and label interval value were not loading correctly.
> fix(number-line): Fix issue with ticks loading | SC-28674

- packages/number-line/configure/src/main.jsx
Fixed react call stack issue when domain is changed and correctAnswers are getting out of range. 
Fix : Moved code block for setting state for Alert Dialog from reloadTicksData to graphChange
> fix(number-line): Fix blank screen on domain change | SC-26467

- packages/graphing/controller/src/index.js
Fixed issue with Graphing Item where Partially added shape are also getting validated. 
https://illuminate.atlassian.net/browse/SC-28876
> fix(graphing): Fix validation issue in Graphing Item | SC-28876

- packages/match/configure/src/answer-config-block.jsx
- packages/match/configure/src/row.jsx
https://illuminate.atlassian.net/browse/PD-3390
> fix(match): fix alignment issues in authoring PD-3390

- packages/multiple-choice/docs/pie-schema.json
- packages/multiple-choice/docs/pie-schema.json.md
- packages/pie-models/src/pie/multiple-choice/index.ts
https://illuminate.atlassian.net/browse/PD-3428
> fix(multiple-choice): update documentation for lockChoiceOrder PD-3428

- packages/number-line/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/number-line/configure/src/main.jsx
- packages/number-line/src/number-line/index.jsx
https://illuminate.atlassian.net/browse/PD-3432
> fix(number-line): remove drawing space for config graph PD-3432

- packages/multiple-choice/src/index.js
- packages/multiple-choice/src/print.js
https://illuminate.atlassian.net/browse/PD-1870
https://illuminate.atlassian.net/browse/PD-2474
> feat(multiple-choice): use math-rendering-accessible PD-1870 PD-2474

- packages/hotspot/controller/src/__tests__/index.test.js
- packages/hotspot/controller/src/defaults.js
- packages/hotspot/controller/src/index.js
- packages/hotspot/controller/src/utils.js
> fix: isResponseCorrect to include circles PD-3458

- packages/graphing/src/__tests__/__snapshots__/main.test.js.snap
- packages/graphing/src/main.jsx
https://illuminate.atlassian.net/browse/PD-3477
> fix(graphing): fallback to graph when size is not set on the model PD-3477

- packages/passage/controller/src/index.js
- packages/passage/docs/demo/generate.js
- packages/passage/src/__tests__/__snapshots__/stimulus-tabs.test.jsx.snap
- packages/passage/src/index.js
- packages/passage/src/print.js
- packages/passage/src/stimulus-tabs.jsx
https://illuminate.atlassian.net/browse/PD-3445
> feat: add support for teacher instructions on passage PD-3445

- packages/number-line/docs/pie-schema.json
- packages/number-line/docs/pie-schema.json.md
- packages/pie-models/src/pie/select-text/index.ts
- packages/select-text/configure/src/__tests__/__snapshots__/design.test.jsx.snap
- packages/select-text/configure/src/defaultConfiguration.js
- packages/select-text/configure/src/design.jsx
- packages/select-text/docs/config-schema.json
- packages/select-text/docs/config-schema.json.md
- packages/select-text/docs/pie-schema.json
- packages/select-text/docs/pie-schema.json.md
https://illuminate.atlassian.net/browse/PD-3506
> feat: Add configuration for custom buttons PD-3506

- packages/matrix/configure/src/Main.jsx
- packages/matrix/configure/src/defaults.js
- packages/matrix/docs/config-schema.json
- packages/matrix/docs/config-schema.json.md
- packages/pie-models/src/pie/matrix/index.ts
https://illuminate.atlassian.net/browse/PD-3508
> feat: Add configuration for custom buttons PD-3508

- packages/math-inline/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/math-inline/configure/src/configure.jsx
- packages/math-inline/configure/src/defaults.js
- packages/math-inline/configure/src/general-config-block.jsx
- packages/math-inline/configure/src/utils.js
- packages/math-inline/docs/config-schema.json
- packages/math-inline/docs/config-schema.json.md
- packages/math-inline/docs/pie-schema.json
- packages/math-inline/docs/pie-schema.json.md
- packages/math-inline/package.json
- packages/pie-models/src/pie/math-inline/index.ts
https://illuminate.atlassian.net/browse/PD-3511
> feat: Add configuration for custom buttons PD-3511

- packages/match/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/match/configure/src/__tests__/__snapshots__/row.test.jsx.snap
- packages/match/configure/src/answer-config-block.jsx
- packages/match/configure/src/configure.jsx
- packages/match/configure/src/defaults.js
- packages/match/configure/src/index.js
- packages/match/configure/src/row.jsx
- packages/match/configure/src/utils.js
- packages/match/docs/config-schema.json
- packages/match/docs/config-schema.json.md
- packages/match/docs/pie-schema.json
- packages/match/docs/pie-schema.json.md
- packages/match/package.json
- packages/pie-models/src/pie/match/index.ts
https://illuminate.atlassian.net/browse/PD-3512
> feat: Add configuration for custom buttons PD-3512

- packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-2457
https://illuminate.atlassian.net/browse/PD-2448
> feat(math-inline): add aria-label for textarea PD-2457

- packages/graphing/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/graphing/configure/src/configure.jsx
- packages/graphing/configure/src/defaults.js
- packages/graphing/controller/src/index.js
- packages/graphing/docs/config-schema.json
- packages/graphing/docs/config-schema.json.md
- packages/graphing/docs/pie-schema.json
- packages/graphing/docs/pie-schema.json.md
- packages/pie-models/src/pie/graphing/index.ts
https://illuminate.atlassian.net/browse/PD-3547
> feat(graphing): add required fields functionality PD-3547

- packages/match/configure/src/configure.jsx
- packages/match/configure/src/defaults.js
- packages/match/controller/src/index.js
- packages/match/docs/config-schema.json
- packages/match/docs/config-schema.json.md
- packages/match/docs/pie-schema.json
- packages/match/docs/pie-schema.json.md
- packages/pie-models/src/pie/match/index.ts
https://illuminate.atlassian.net/browse/PD-3548
> feat(match): add required fields functionality PD-3548

- packages/categorize/configure/src/defaults.js
- packages/categorize/configure/src/design/index.jsx
- packages/categorize/controller/src/index.js
- packages/categorize/docs/config-schema.json
- packages/categorize/docs/config-schema.json.md
- packages/categorize/docs/pie-schema.json
- packages/categorize/docs/pie-schema.json.md
- packages/pie-models/src/pie/categorize/index.ts
https://illuminate.atlassian.net/browse/PD-3546
> feat(categorize): add required fields functionality PD-3546

- packages/charting/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/charting/configure/src/configure.jsx
- packages/charting/configure/src/defaults.js
- packages/charting/docs/config-schema.json
- packages/charting/docs/config-schema.json.md
- packages/charting/docs/pie-schema.json
- packages/charting/docs/pie-schema.json.md
- packages/charting/package.json
- packages/pie-models/src/pie/charting/index.ts
https://illuminate.atlassian.net/browse/PD-3515
> feat: Add configuration for custom buttons PD-3515

- packages/hotspot/configure/src/__tests__/__snapshots__/root.test.js.snap
- packages/hotspot/configure/src/defaults.js
- packages/hotspot/configure/src/root.jsx
- packages/hotspot/docs/config-schema.json
- packages/hotspot/docs/config-schema.json.md
- packages/hotspot/docs/pie-schema.json
- packages/hotspot/docs/pie-schema.json.md
- packages/pie-models/src/pie/hotspot/index.ts
https://illuminate.atlassian.net/browse/PD-3523
> feat: Add configuration for custom buttons PD-3523

- packages/image-cloze-association/configure/src/defaults.js
- packages/image-cloze-association/configure/src/root.jsx
- packages/image-cloze-association/docs/config-schema.json
- packages/image-cloze-association/docs/config-schema.json.md
- packages/image-cloze-association/docs/pie-schema.json
- packages/image-cloze-association/docs/pie-schema.json.md
- packages/pie-models/src/pie/image-cloze-association/index.ts
https://illuminate.atlassian.net/browse/PD-3524
> feat: Add configuration for custom buttons PD-3524

- packages/match/configure/src/index.js
https://illuminate.atlassian.net/browse/PD-3558
> fix(match): check for pie-author when configuration is set PD-3558

- packages/graphing-solution-set/controller/src/index.js
Added fix to validation logic for GSS item in controller/index.js
> fix(graphing-solution-set): Fix issue with validation logic SC-29578

- packages/categorize/configure/src/design/utils.js
- packages/charting/configure/src/configure.jsx
- packages/drawing-response/configure/src/root.jsx
- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/explicit-constructed-response/configure/src/defaults.js
- packages/explicit-constructed-response/configure/src/main.jsx
- packages/explicit-constructed-response/docs/config-schema.json
- packages/explicit-constructed-response/docs/config-schema.json.md
- packages/explicit-constructed-response/docs/pie-schema.json
- packages/explicit-constructed-response/docs/pie-schema.json.md
- packages/explicit-constructed-response/package.json
- packages/graphing/configure/src/configure.jsx
- packages/hotspot/configure/src/root.jsx
- packages/image-cloze-association/configure/src/root.jsx
- packages/match/configure/src/utils.js
- packages/math-inline/configure/src/utils.js
- packages/matrix/configure/src/Main.jsx
- packages/multiple-choice/configure/src/main.jsx
- packages/number-line/configure/src/main.jsx
- packages/pie-models/src/pie/explicit-constructed-response/index.ts
- packages/select-text/configure/src/design.jsx
https://illuminate.atlassian.net/browse/PD-3520
> feat: Add configuration for custom buttons PD-3520

- packages/graphing-solution-set/docs/config-schema.json
- packages/graphing-solution-set/docs/config-schema.json.md
- packages/graphing-solution-set/docs/pie-schema.json
- packages/graphing-solution-set/docs/pie-schema.json.md
- packages/pie-models/src/pie/select-text/index.ts
- packages/select-text/configure/src/__tests__/__snapshots__/design.test.jsx.snap
- packages/select-text/configure/src/defaultConfiguration.js
- packages/select-text/configure/src/design.jsx
- packages/select-text/controller/src/index.js
- packages/select-text/docs/config-schema.json
- packages/select-text/docs/config-schema.json.md
- packages/select-text/docs/pie-schema.json
- packages/select-text/docs/pie-schema.json.md
https://illuminate.atlassian.net/browse/PD-3565
> feat(select-text): add required fields functionality PD-3565

- packages/passage/src/stimulus-tabs.jsx
https://illuminate.atlassian.net/browse/PD-3394
> fix(passage): use white background and black text for tabs (temporary fix) PD-3394

- packages/match/configure/src/row.jsx
- packages/match/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-3570
> fix(match): update validation to work with image, audio and video content PD-3570

- packages/match/configure/src/answer-config-block.jsx
- packages/match/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-3570
> fix(match): exclude column errors if no error occurred PD-3570

- packages/likert/configure/src/defaults.js
- packages/likert/configure/src/main.jsx
- packages/likert/docs/config-schema.json
- packages/likert/docs/config-schema.json.md
- packages/likert/docs/pie-schema.json
- packages/likert/docs/pie-schema.json.md
- packages/pie-models/src/pie/likert/index.ts
https://illuminate.atlassian.net/browse/PD-3513
> feat: Add configuration for custom buttons PD-3513

- packages/extended-text-entry/configure/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/configure/src/defaults.js
- packages/extended-text-entry/configure/src/main.jsx
- packages/extended-text-entry/docs/config-schema.json
- packages/extended-text-entry/docs/config-schema.json.md
- packages/extended-text-entry/docs/pie-schema.json
- packages/extended-text-entry/docs/pie-schema.json.md
- packages/pie-models/src/pie/extended-text-entry/index.ts
https://illuminate.atlassian.net/browse/PD-3521
> feat: Add configuration for custom buttons PD-3521

- packages/math-inline/configure/src/__tests__/__snapshots__/configure.test.js.snap
- packages/math-inline/configure/src/configure.jsx
- packages/math-inline/configure/src/defaults.js
- packages/math-inline/configure/src/general-config-block.jsx
- packages/math-inline/controller/src/index.js
- packages/math-inline/docs/config-schema.json
- packages/math-inline/docs/config-schema.json.md
- packages/math-inline/docs/pie-schema.json
- packages/math-inline/docs/pie-schema.json.md
- packages/pie-models/src/pie/math-inline/index.ts
https://illuminate.atlassian.net/browse/PD-3576
> feat(math-inline): add required fields functionality PD-3576

- packages/ebsr/configure/src/defaults.js
- packages/ebsr/docs/config-schema.json
- packages/ebsr/docs/config-schema.json.md
- packages/ebsr/docs/pie-schema.json
- packages/ebsr/docs/pie-schema.json.md
- packages/pie-models/src/pie/ebsr/index.ts
https://illuminate.atlassian.net/browse/PD-3519
> feat: Add configuration for custom buttons PD-3519

- packages/hotspot/configure/src/__tests__/__snapshots__/root.test.js.snap
- packages/hotspot/configure/src/defaults.js
- packages/hotspot/configure/src/root.jsx
- packages/hotspot/controller/src/index.js
- packages/hotspot/docs/config-schema.json
- packages/hotspot/docs/config-schema.json.md
- packages/hotspot/docs/pie-schema.json
- packages/hotspot/docs/pie-schema.json.md
- packages/pie-models/src/pie/hotspot/index.ts
https://illuminate.atlassian.net/browse/PD-3580
> feat(hotspot): added required fields functionality PD-3580

- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/explicit-constructed-response/configure/src/defaults.js
- packages/explicit-constructed-response/configure/src/main.jsx
- packages/explicit-constructed-response/controller/src/index.js
- packages/explicit-constructed-response/docs/config-schema.json
- packages/explicit-constructed-response/docs/config-schema.json.md
- packages/explicit-constructed-response/docs/pie-schema.json
- packages/explicit-constructed-response/docs/pie-schema.json.md
- packages/pie-models/src/pie/explicit-constructed-response/index.ts
https://illuminate.atlassian.net/browse/PD-3583
> feat(explicit-constructed-response): add required fields functionality PD-3583

- packages/drag-in-the-blank/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/drag-in-the-blank/configure/src/defaults.js
- packages/drag-in-the-blank/configure/src/main.jsx
- packages/drag-in-the-blank/controller/src/index.js
- packages/drag-in-the-blank/docs/config-schema.json
- packages/drag-in-the-blank/docs/config-schema.json.md
- packages/drag-in-the-blank/docs/pie-schema.json
- packages/drag-in-the-blank/docs/pie-schema.json.md
- packages/pie-models/src/pie/drag-in-the-blank/index.ts
https://illuminate.atlassian.net/browse/PD-3584
> feat(drag-in-the-blank): add required fields functionality PD-3584

- packages/drawing-response/configure/src/__tests__/__snapshots__/root.test.jsx.snap
- packages/drawing-response/configure/src/defaults.js
- packages/drawing-response/configure/src/root.jsx
- packages/drawing-response/controller/src/index.js
- packages/drawing-response/docs/config-schema.json
- packages/drawing-response/docs/config-schema.json.md
- packages/drawing-response/docs/pie-schema.json
- packages/drawing-response/docs/pie-schema.json.md
- packages/pie-models/src/pie/drawing-response/index.ts
https://illuminate.atlassian.net/browse/PD-3589
> feat(drawing-response): add required fields functionality PD-3589

- packages/image-cloze-association/configure/src/defaults.js
- packages/image-cloze-association/configure/src/root.jsx
- packages/image-cloze-association/controller/src/index.js
- packages/image-cloze-association/docs/config-schema.json
- packages/image-cloze-association/docs/config-schema.json.md
- packages/image-cloze-association/docs/pie-schema.json
- packages/image-cloze-association/docs/pie-schema.json.md
- packages/pie-models/src/pie/image-cloze-association/index.ts
https://illuminate.atlassian.net/browse/PD-3591
> feat(image-cloze-association): add required fields functionality PD-3591

- packages/matrix/configure/src/Main.jsx
- packages/matrix/configure/src/defaults.js
- packages/matrix/controller/src/index.js
- packages/matrix/docs/config-schema.json
- packages/matrix/docs/config-schema.json.md
- packages/pie-models/src/pie/matrix/index.ts
https://illuminate.atlassian.net/browse/PD-3596
> feat(matrix): add required fields functionality PD-3596

- packages/categorize/controller/src/index.js
- packages/categorize/controller/src/utils.js
- packages/charting/controller/src/index.js
- packages/graphing/controller/src/index.js
- packages/inline-dropdown/controller/src/index.js
- packages/number-line/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-3571
> fix: update validation to work with images, audio and video content PD-3571

- packages/multiple-choice/configure/src/defaults.js
- packages/multiple-choice/configure/src/main.jsx
- packages/multiple-choice/controller/src/index.js
- packages/multiple-choice/docs/config-schema.json
- packages/multiple-choice/docs/config-schema.json.md
- packages/multiple-choice/docs/pie-schema.json
- packages/multiple-choice/docs/pie-schema.json.md
- packages/pie-models/src/pie/multiple-choice/index.ts
https://illuminate.atlassian.net/browse/PD-3572
> feat(multiple-choice): add required fields functionality PD-3572

- packages/hotspot/controller/src/utils.js
https://illuminate.atlassian.net/browse/PD-3604
> fix: Add sanity check for score calculation on shapes PD-3604

- packages/drag-in-the-blank/configure/src/choices.jsx
- packages/drag-in-the-blank/configure/src/main.jsx
https://illuminate.atlassian.net/browse/PD-3578
> fix(drag-in-the-blank): added imageSupport for addChoice

- packages/inline-dropdown/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/inline-dropdown/configure/src/defaults.js
- packages/inline-dropdown/configure/src/main.jsx
- packages/inline-dropdown/docs/config-schema.json
- packages/inline-dropdown/docs/config-schema.json.md
- packages/inline-dropdown/docs/pie-schema.json
- packages/inline-dropdown/docs/pie-schema.json.md
- packages/inline-dropdown/package.json
- packages/pie-models/src/pie/inline-dropdown/index.ts
https://illuminate.atlassian.net/browse/PD-3525
> feat: Add configuration for custom buttons PD-3525

- packages/pie-models/src/pie/placement-ordering/index.ts
- packages/placement-ordering/configure/src/__tests__/__snapshots__/design.test.jsx.snap
- packages/placement-ordering/configure/src/choice-editor.jsx
- packages/placement-ordering/configure/src/choice-tile.jsx
- packages/placement-ordering/configure/src/defaults.js
- packages/placement-ordering/configure/src/design.jsx
- packages/placement-ordering/docs/config-schema.json
- packages/placement-ordering/docs/config-schema.json.md
- packages/placement-ordering/docs/pie-schema.json
- packages/placement-ordering/docs/pie-schema.json.md
https://illuminate.atlassian.net/browse/PD-3528
> feat: Add configuration for custom buttons PD-3528

- packages/graphing/configure/src/index.js
- packages/number-line/configure/src/index.js
https://illuminate.atlassian.net/browse/PD-3614
> fix: check for pie-author when configuration is set PD-3614

- packages/explicit-constructed-response/controller/src/defaults.js
- packages/explicit-constructed-response/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-3544
> fix(explicit-constructed-respone): update controller defaults PD-3544

- packages/multi-trait-rubric/configure/src/common.jsx
- packages/multi-trait-rubric/configure/src/index.js
- packages/multi-trait-rubric/configure/src/traitsHeader.jsx
https://illuminate.atlassian.net/browse/PD-3579
> fix(multi-trait-rubric): fixed validation error layout, fixed some prop types mismatch, removed console log PD-3579

- packages/graphing/docs/demo/generate.js
https://illuminate.atlassian.net/browse/PD-3382
> chore: update graphing model in demo file PD-3382

- packages/multi-trait-rubric/configure/src/__tests__/index.test.jsx
- packages/multi-trait-rubric/configure/src/index.js
- packages/rubric/configure/src/__tests__/index.test.jsx
- packages/rubric/configure/src/index.js
https://illuminate.atlassian.net/browse/PD-3608
> Feat(rubric; multi-trait-rubric) : implement tests and adjustments in validateModel method

- packages/charting/configure/src/charting-config.jsx
- packages/charting/configure/src/configure.jsx
- packages/charting/controller/src/index.js
- packages/charting/docs/config-schema.json
- packages/charting/docs/config-schema.json.md
- packages/graphing-solution-set/configure/src/__tests__/__snapshots__/correct-response.test.js.snap
- packages/graphing-solution-set/configure/src/correct-response.jsx
- packages/pie-models/src/pie/charting/index.ts
1. Implemented axis label character limit settings for Charting item
2. Added extra prop on outcome object for scores API for relative scoring
3. Punctuation fix in GSS item.
https://illuminate.atlassian.net/browse/SC-29795
https://illuminate.atlassian.net/browse/SC-30682
> feat(charting, graphing-solution-set): Charting Item Relative Scoring and Label Characters Limit SC-29795, SC-30682

- packages/inline-dropdown/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/inline-dropdown/configure/src/__tests__/main.test.jsx
- packages/inline-dropdown/configure/src/main.jsx
https://illuminate.atlassian.net/browse/PD-3329
https://illuminate.atlassian.net/browse/PD-3330
> fix(inline-dropdown): update responses comparison PD-3329 PD-3330

- packages/extended-text-entry/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/src/main.jsx
https://illuminate.atlassian.net/browse/PD-3709
> fix(extended-text-entry): add characters limit of 50000 PD-3709

- packages/multiple-choice/src/choice-input.jsx
https://illuminate.atlassian.net/browse/PD-3626
> fix(multiple-choice): fix styling for disabled choices PD-3626

- packages/math-templated/configure/src/design.jsx
- packages/math-templated/controller/src/index.js
- packages/math-templated/docs/demo/session.js
- packages/math-templated/src/index.js
- packages/math-templated/src/main.jsx
1. Removed some logs
2. Hardcoded feedback (even response area are correct, odd response area are incorrect)
3. Fix sessions not getting updated
4. Fix "more than 10 responses areas rendering _undefined_ issue":
5. Correctness indicators
6. Show correct answer
> feat: show correctness, fix: update sessions according to model

- packages/math-templated/configure/src/design.jsx
- packages/math-templated/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-3805
> feat(math-templated): add validation method PD-3805

- packages/math-inline/src/main.jsx
> fix(math-inline): add sanity check to prevent player crash if response template content is deleted

- packages/graphing/controller/src/__tests__/index.test.js
- packages/graphing/controller/src/index.js
- packages/graphing/controller/src/utils.js
- packages/graphing/src/__tests__/__snapshots__/main.test.js.snap
- packages/graphing/src/main.jsx
https://illuminate.atlassian.net/browse/PD-3735
> Feat(graphing): Design Changes for Graphing Evaluate PD-3735

- packages/passage/docs/demo/generate.js
- packages/passage/src/__tests__/__snapshots__/stimulus-tabs.test.jsx.snap
- packages/passage/src/index.js
- packages/passage/src/print.js
- packages/passage/src/stimulus-tabs.jsx
https://illuminate.atlassian.net/browse/PD-2928
> feat(passage): add support for subtitle and author + cleanup PD-2928

- packages/graphing-solution-set/configure/src/graphing-config.jsx
fix(graphing-solution-set): Fixed issue with Alert PopUp
JIRA - https://illuminate.atlassian.net/browse/SC-31533
> fix(graphing-solution-set): Fixed issue with Alert PopUp

- packages/math-inline/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1273
> fix(math-inline): test controller model function execution

- packages/math-inline/controller/src/index.js
Reverts pie-framework/pie-elements#1970
> Revert "fix(math-inline): test controller model function execution"

- packages/math-inline/controller/src/__tests__/index.test.jsx
Reverts pie-framework/pie-elements#1971
> Revert "fix(math-inline): disable tests WIP PD-1273"

- packages/math-templated/configure/src/__tests__/__snapshots__/design.test.js.snap
- packages/math-templated/configure/src/__tests__/__snapshots__/response.test.js.snap
- packages/math-templated/configure/src/__tests__/design.test.js
- packages/math-templated/configure/src/__tests__/response.test.js
- packages/math-templated/configure/src/design.jsx
- packages/math-templated/configure/src/response.jsx
- packages/math-templated/controller/src/__tests__/index.test.jsx
- packages/math-templated/controller/src/index.js
- packages/math-templated/src/__tests__/__snapshots__/main.test.js.snap
- packages/math-templated/src/__tests__/main.test.js
https://illuminate.atlassian.net/browse/PD-3807
> Feat(math-templated): Unit tests

- packages/math-templated/docs/config-schema.json
- packages/math-templated/docs/config-schema.json.md
- packages/math-templated/docs/pie-schema.json
- packages/math-templated/docs/pie-schema.json.md
- packages/pie-models/src/pie/math-templated/index.ts
https://illuminate.atlassian.net/browse/PD-3838
> feat(math-templated): Added documentation PD-3838

- packages/passage/configure/src/__tests__/__snapshots__/main.test.js.snap
- packages/passage/configure/src/defaults.js
- packages/passage/configure/src/design.jsx
fix: made sure only passage text has access to h3 and blockquote [PD-3878]
https://illuminate.atlassian.net/browse/PD-3878
> fix: made sure only passage text has access to h3 and blockquote [PD-3878]

- packages/explicit-constructed-response/controller/src/index.js
- packages/explicit-constructed-response/src/main.js
https://illuminate.atlassian.net/browse/PD-3798
> fix(ECR): using specific imports PD-3798

- packages/charting/controller/src/index.js
- packages/charting/docs/demo/generate.js
- packages/charting/src/__tests__/__snapshots__/main.test.js.snap
- packages/charting/src/main.jsx
https://illuminate.atlassian.net/browse/PD-3898
> fix(charting): hide correct answer toggle when answer is correct PD-3898

- packages/number-line/controller/src/defaults.js
https://illuminate.atlassian.net/browse/PD-3934
> fix(number-line): clean up controller defaults initialElements PD-3934

- packages/select-text/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-3882
> fix(select-text): update tokens validation and cleanup PD-3882

- packages/number-line/src/number-line/index.jsx
- packages/passage/src/index.js
https://illuminate.atlassian.net/browse/PD-3885
> fix(passage): render math content in student side PD-3885

- packages/drag-in-the-blank/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/drag-in-the-blank/configure/src/defaults.js
- packages/drag-in-the-blank/configure/src/main.jsx
- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/explicit-constructed-response/configure/src/defaults.js
- packages/extended-text-entry/configure/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/configure/src/defaults.js
- packages/inline-dropdown/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/inline-dropdown/configure/src/defaults.js
- packages/math-templated/configure/src/__tests__/__snapshots__/design.test.js.snap
- packages/math-templated/configure/src/defaults.js
https://illuminate.atlassian.net/browse/PD-3878
> fix: removed h3 and blockquote from ecr [PD-3878]

- packages/number-line/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/number-line/controller/src/index.js
- packages/number-line/src/number-line/index.jsx
https://illuminate.atlassian.net/browse/PD-3933
> feat(number-line): add teacher instructions to player side PD-3933

- packages/number-line/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/number-line/configure/src/__tests__/main.test.jsx
- packages/number-line/configure/src/defaults.js
- packages/number-line/configure/src/index.js
- packages/number-line/configure/src/main.jsx
- packages/number-line/docs/config-schema.json
- packages/number-line/docs/config-schema.json.md
- packages/number-line/docs/pie-schema.json
- packages/number-line/docs/pie-schema.json.md
- packages/pie-models/src/pie/number-line/index.ts
https://illuminate.atlassian.net/browse/PD-3932
> feat(number-line): add Settings Panel and authoring view settings PD-3932

- packages/categorize/configure/src/defaults.js
- packages/categorize/configure/src/design/__tests__/__snapshots__/header.test.jsx.snap
- packages/categorize/configure/src/design/__tests__/__snapshots__/index.test.jsx.snap
- packages/categorize/configure/src/design/choices/__tests__/__snapshots__/index.test.jsx.snap
- packages/categorize/configure/src/design/choices/__tests__/index.test.jsx
- packages/categorize/configure/src/design/choices/index.jsx
- packages/categorize/configure/src/design/header.jsx
- packages/categorize/configure/src/design/index.jsx
- packages/categorize/configure/src/index.js
- packages/categorize/controller/src/defaults.js
- packages/categorize/controller/src/index.js
- packages/categorize/docs/config-schema.json
- packages/categorize/docs/config-schema.json.md
- packages/categorize/docs/pie-schema.json
- packages/categorize/docs/pie-schema.json.md
- packages/pie-models/src/pie/categorize/index.ts
https://illuminate.atlassian.net/browse/PD-3003
> feat(categorize): Categorize authoring view settings should include a maxAnswerChoices property PD-3003

- packages/ebsr/package.json
- packages/ebsr/src/print.js
https://illuminate.atlassian.net/browse/PD-3973
> fix(ebsr): add part labels logic to print PD-3973

- packages/match/configure/src/row.jsx
- packages/match/src/answer-grid.jsx
https://illuminate.atlassian.net/browse/PD-3982
> fix: made sure checkbox fills the available width [PD-3982]

- packages/image-cloze-association/src/image-container.jsx
- packages/image-cloze-association/src/interactive-section.jsx
- packages/image-cloze-association/src/possible-response.jsx
- packages/image-cloze-association/src/possible-responses.jsx
- packages/image-cloze-association/src/root.jsx
https://illuminate.atlassian.net/browse/PD-3955
> fix(image-cloze-association): adjust possible response area width PD-3955

- packages/passage/src/__tests__/__snapshots__/stimulus-tabs.test.jsx.snap
- packages/passage/src/stimulus-tabs.jsx
https://illuminate.atlassian.net/browse/PD-4006
> fix(passage): collapse normal spaces PD-4006

- packages/passage/controller/src/defaults.js
- packages/passage/controller/src/index.js
- packages/passage/src/index.js
- packages/passage/src/print.js
- packages/passage/src/stimulus-tabs.jsx
https://illuminate.atlassian.net/browse/PD-4058
https://illuminate.atlassian.net/browse/PD-4006
> fix(passage): add possibility to enable/disable fields in player PD-4006 PD-4058

- packages/passage/configure/src/__tests__/__snapshots__/main.test.js.snap
- packages/passage/configure/src/__tests__/main.test.js
- packages/passage/configure/src/defaults.js
- packages/passage/configure/src/design.jsx
- packages/passage/controller/package.json
- packages/passage/controller/src/defaults.js
- packages/passage/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-4068
https://illuminate.atlassian.net/browse/PD-4006
> fix(passage): fix validation and update controller default values PD-4068 PD-4006

- packages/fraction-model/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/fraction-model/configure/src/main.jsx
- packages/fraction-model/src/index.js
https://illuminate.atlassian.net/browse/SC-30716
> fix(fraction-model): update wrong import SC-30716

- packages/fraction-model/configure/src/__tests__/main.test.jsx
- packages/fraction-model/configure/src/main.jsx
- packages/fraction-model/src/__tests__/main.test.jsx
- packages/fraction-model/src/fraction-model-chart.js
- packages/fraction-model/src/main.jsx
Fixed issue related to key attribute for Fraction Model Chart component
> fix(fraction-model): Fixed chart not rendering after saving item SC-30716

- packages/categorize/src/categorize/choice.jsx
- packages/match-list/src/answer.js
https://illuminate.atlassian.net/browse/PD-4042
> feat(categorize,match-list): white background for answer choices PD-4042

- packages/match/controller/src/index.js
Fixed issue #4 from https://illuminate.atlassian.net/browse/SC-28887
> fix(match): Validation fix for duplicate column header

- packages/passage/controller/src/defaults.js
- packages/passage/src/print.js
https://illuminate.atlassian.net/browse/PD-4148
> fix(passage): fix print not working PD-4148

- packages/multiple-choice/src/choice-input.jsx
https://illuminate.atlassian.net/browse/PD-4037
> feat(multiple-choice): set letter spacing to normal to fix PD-4037

- packages/inline-dropdown/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/inline-dropdown/configure/src/main.jsx
- packages/inline-dropdown/configure/src/response-area.jsx
https://illuminate.atlassian.net/browse/PD-4232
> fix(inline-dropdown): extracted ResponseArea into a separate component to ensure renderMath is called on re-render PD-4232

- packages/match/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-3858
> fix(match): fix validation message for maxLengthAnswers PD-3858

- packages/passage/src/stimulus-tabs.jsx
https://illuminate.atlassian.net/browse/PD-4236
> fix(passage): add purpose for text PD-4236

- packages/categorize/src/categorize/category.jsx
https://illuminate.atlassian.net/browse/PD-4185
> fix(categorize): show green border if category is correct PD-4185

- packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-4205
> fix(math-inline): iPad - Student View stopped working if student enters values in more than one response area PD-4205

- packages/fraction-model/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/fraction-model/configure/src/__tests__/main.test.jsx
- packages/fraction-model/configure/src/index.js
- packages/fraction-model/configure/src/main.jsx
- packages/fraction-model/src/main.jsx
Preview prompt used for title and prompt to fix TTS issue
> fix: preview prompt used for title and prompt to fix TTS issue

- packages/categorize/configure/src/design/__tests__/__snapshots__/header.test.jsx.snap
- packages/categorize/configure/src/design/header.jsx
https://illuminate.atlassian.net/browse/PD-4184
> fix(categorize): Added  `enterTouchDelay` and `leaveTouchDelay` to improve UX on touch devices PD-4184

- packages/placement-ordering/configure/src/choice-tile.jsx
https://illuminate.atlassian.net/browse/PD-4206
> fix(placement-ordering): added autoWidthToolbar to fix choices toolbar PD-4206

- packages/match-list/docs/demo/generate.js
https://illuminate.atlassian.net/browse/PD-4191
George gave me this new model for match-list. The other one was relying on a image that was broken
> fix(match-list): update demo model. current one was broken PD-4191

- packages/passage/docs/demo/generate.js
- packages/passage/src/stimulus-tabs.jsx
https://illuminate.atlassian.net/browse/PD-4274
> fix(passage): check for content value as it is PD-4274

- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/explicit-constructed-response/configure/src/main.jsx
https://illuminate.atlassian.net/browse/PD-4187 - see comment section.
> fix(ECR): add autoWidthToolbar to all ECR input toolbars PD-4187

- packages/placement-ordering/controller/src/index.js
- packages/placement-ordering/controller/src/scoring.js
https://illuminate.atlassian.net/browse/PD-4211
> fix(placement-ordering): add sanity check on scoring PD-4211

- packages/drag-in-the-blank/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/drag-in-the-blank/configure/src/choices.jsx
- packages/drag-in-the-blank/configure/src/defaults.js
- packages/drag-in-the-blank/configure/src/main.jsx
- packages/drag-in-the-blank/docs/config-schema.json
- packages/drag-in-the-blank/docs/config-schema.json.md
- packages/pie-models/src/pie/drag-in-the-blank/index.ts
https://illuminate.atlassian.net/browse/PD-4207
> feat(ditb): added 2 new properties to limit text and images in answer choices PD-4207

- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/alternateResponses.test.jsx.snap
- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/alternateSection.test.jsx.snap
- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/ecr-toolbar.test.jsx.snap
- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/main.test.jsx.snap
- packages/explicit-constructed-response/configure/src/__tests__/ecr-toolbar.test.jsx
- packages/explicit-constructed-response/configure/src/alternateResponses.jsx
- packages/explicit-constructed-response/configure/src/alternateSection.jsx
- packages/explicit-constructed-response/configure/src/defaults.js
- packages/explicit-constructed-response/configure/src/ecr-toolbar.jsx
- packages/explicit-constructed-response/configure/src/index.js
- packages/explicit-constructed-response/configure/src/main.jsx
- packages/explicit-constructed-response/configure/src/markupUtils.js
- packages/explicit-constructed-response/controller/src/index.js
- packages/explicit-constructed-response/docs/config-schema.json
- packages/explicit-constructed-response/docs/config-schema.json.md
- packages/explicit-constructed-response/docs/pie-schema.json
- packages/explicit-constructed-response/docs/pie-schema.json.md
- packages/explicit-constructed-response/src/index.js
- packages/explicit-constructed-response/src/main.js
- packages/pie-models/src/pie/explicit-constructed-response/index.ts
https://illuminate.atlassian.net/browse/PD-4004
> Feat(ECR): option to include Spanish characters - respArea changed to EditableHtml PD-4004 

- packages/passage/controller/src/index.js
- packages/passage/src/print.js
https://illuminate.atlassian.net/browse/PD-4346
> override root-level config with passage-level config PD-4346

- packages/explicit-constructed-response/configure/src/ecr-toolbar.jsx
https://illuminate.atlassian.net/browse/PD-4372
> fix(ECR): adjust style for ECR response area PD-4372

- packages/categorize/configure/src/design/categories/__tests__/__snapshots__/choice-preview.test.jsx.snap
- packages/categorize/configure/src/design/categories/choice-preview.jsx
- packages/charting/configure/src/charting-config.jsx
- packages/complex-rubric/configure/src/__tests__/index.test.js
- packages/complex-rubric/configure/src/__tests__/main.test.jsx
- packages/complex-rubric/configure/src/main.jsx
- packages/likert/configure/src/main.jsx
- packages/match/configure/src/row.jsx
- packages/math-inline/configure/src/response.jsx
- packages/math-templated/configure/src/response.jsx
- packages/matrix/configure/src/MatrixLabelTypeHeaderInput.js
- packages/number-line/configure/src/ticks.jsx
- packages/placement-ordering/configure/src/choice-tile.jsx
- packages/rubric/configure/src/pie-toolbox-rubric/authoring.jsx
https://illuminate.atlassian.net/browse/PD-4334
> feat: In PIE authoring UIs, change color of various controls from pink to blue

- packages/placement-ordering/src/tile.jsx
https://illuminate.atlassian.net/browse/PD-4408
> fix(placement-ordering): revert changes for the fix in PD-3656 - transform: translateZ(0px) PD-4408

- packages/extended-text-entry/configure/src/defaults.js
- packages/extended-text-entry/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/src/main.jsx
https://illuminate.atlassian.net/browse/PD-4329
> feat(extended-text-entry): disable table from editable-html toolbar PD-4329

- packages/match/configure/src/index.js
https://illuminate.atlassian.net/browse/PD-4486
> fix(match): correct logic for setting inputConfiguration to Rows PD-4486

- packages/select-text/configure/src/defaultConfiguration.js
- packages/select-text/controller/src/defaults.js
https://illuminate.atlassian.net/browse/PD-4450
> fix(select-text): allow students to select multiple answers when maxSelection is missing from the model PD-4450

- packages/passage/configure/src/defaults.js
- packages/passage/controller/src/defaults.js
- packages/passage/src/print.js
https://illuminate.atlassian.net/browse/PD-4515
> fix(passage): enable title and subtitle from controller by default PD-4515

- packages/categorize/configure/src/defaults.js
- packages/categorize/controller/src/defaults.js
- packages/categorize/controller/src/index.js
- packages/categorize/src/categorize/__tests__/__snapshots__/droppable-placeholder.test.jsx.snap
- packages/categorize/src/categorize/categories.jsx
- packages/categorize/src/categorize/category.jsx
- packages/categorize/src/categorize/droppable-placeholder.jsx
https://illuminate.atlassian.net/browse/PD-4368
> feat(categorize): add minRowHeight on model PD-4368

- packages/categorize/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-4499
> feat(categorize): migrate ui_style row_min_height to minRowHeight PD-4499

- packages/drag-in-the-blank/configure/src/index.js
https://illuminate.atlassian.net/browse/PD-4623
> fix: made sure top level element is block, not inline [PD-4623]

- packages/explicit-constructed-response/configure/src/ecr-toolbar.jsx
https://illuminate.atlassian.net/browse/PD-4618
Fixed console error message.
> fix(ECR): small cleanup & fixed console error message PD-4618

- packages/math-inline/controller/package.json
- packages/math-templated/controller/package.json
- yarn.lock
https://illuminate.atlassian.net/browse/PD-4410
> fix: update @pie-framework/math-validation PD-4410

- packages/image-cloze-association/src/root.jsx
https://illuminate.atlassian.net/browse/PD-4587
> fix(ICA): show correct answers highlighted with green color PD-4587

- packages/image-cloze-association/src/possible-response.jsx
https://illuminate.atlassian.net/browse/PD-4532
> fix(ica): Use defaultClassName instead of className to ensure styles are applied in PreviewPrompt PD-4532

- packages/categorize/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-4499
> feat(categorize): revert PD-4499

- packages/categorize/src/__tests__/index.test.js
- packages/categorize/src/index.js
- packages/drag-in-the-blank/src/index.js
- packages/hotspot/src/index.js
- packages/image-cloze-association/src/index.js
https://illuminate.atlassian.net/browse/PD-4610
> update session complete condition PD-4610

- packages/multiple-choice/controller/src/index.js
- packages/multiple-choice/docs/demo/generate.js
- packages/multiple-choice/docs/pie-schema.json
- packages/multiple-choice/docs/pie-schema.json.md
- packages/multiple-choice/src/choice-input.jsx
- packages/multiple-choice/src/choice.jsx
- packages/multiple-choice/src/index.js
- packages/multiple-choice/src/multiple-choice.jsx
- packages/pie-models/src/pie/multiple-choice/index.ts
https://illuminate.atlassian.net/browse/PD-3843
https://illuminate.atlassian.net/browse/PD-4518
> feat(multiple-choice): add min/max selection possibility PD-3843 PD-4518

- packages/categorize/src/__tests__/index.test.js
- packages/drag-in-the-blank/src/__tests__/__snapshots__/index.test.js.snap
- packages/drag-in-the-blank/src/__tests__/index.test.js
- packages/drag-in-the-blank/src/index.js
- packages/hotspot/src/__tests__/__snapshots__/index.test.js.snap
- packages/hotspot/src/__tests__/index.test.js
- packages/hotspot/src/session-updater.js
- packages/image-cloze-association/src/__tests__/__snapshots__/index.test.js.snap
- packages/image-cloze-association/src/__tests__/index.test.js
- packages/multiple-choice/src/__tests__/index-test.jsx
- packages/multiple-choice/src/index.js
https://illuminate.atlassian.net/browse/PD-4665
> feat: add tests for session changed operation PD-4665

- packages/multiple-choice/configure/src/__tests__/__snapshots__/root.test.jsx.snap
- packages/multiple-choice/configure/src/defaults.js
- packages/multiple-choice/configure/src/main.jsx
- packages/multiple-choice/controller/src/defaults.js
- packages/multiple-choice/controller/src/index.js
- packages/multiple-choice/controller/src/utils.js
- packages/multiple-choice/docs/demo/generate.js
- packages/multiple-choice/src/choice-input.jsx
https://illuminate.atlassian.net/browse/PD-4552
> fix(multiple-choice): Improve reading of responses, removed the redundant accessibility prop from choices PD-4552

- packages/number-line/src/number-line/graph/elements/line.jsx
- packages/number-line/src/number-line/graph/elements/ray.jsx
https://illuminate.atlassian.net/browse/PD-4590
> fix(number-line): for line & ray fix click on edges for selection PD-4590

- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/alternateSection.test.jsx.snap
- packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/ecr-toolbar.test.jsx.snap
- packages/explicit-constructed-response/configure/src/alternateSection.jsx
- packages/explicit-constructed-response/configure/src/ecr-toolbar.jsx
https://illuminate.atlassian.net/browse/PD-4616
> fix(ECR): hide editable html toolbar in ECR if characters are not enabled PD-4616

- packages/extended-text-entry/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/src/main.jsx
https://illuminate.atlassian.net/browse/PD-4687
> fix(extended-text-entry): fix student's view editor toolbar

- packages/multiple-choice/src/index.js
- packages/multiple-choice/src/multiple-choice.jsx
https://illuminate.atlassian.net/browse/PD-4677
> fix(multiple-choice): use session as source of truth for selected answers PD-4677

- packages/multiple-choice/package.json
- packages/multiple-choice/src/__tests__/index-test.jsx
- packages/multiple-choice/src/index.js
https://illuminate.atlassian.net/browse/PD-4677
> fix(multiple-choice): add minSelections default value and update events PD-4677

- packages/multiple-choice/src/choice-input.jsx
https://illuminate.atlassian.net/browse/PD-4727
> fix(multiple-choice): prevent dots from rendering unless a display key is explicitly provided PD-4727

- packages/multiple-choice/src/index.js
fix for https://illuminate.atlassian.net/browse/PD-4452
> fix(multiple-choice): fix click issue in autoplay PD-4452

- packages/multiple-choice/src/index.js
https://illuminate.atlassian.net/browse/PD-4740
> fix(multiple-choice): check for autoplay to be enabled PD-4740

- packages/multiple-choice/src/index.js
https://illuminate.atlassian.net/browse/PD-4761
https://github.com/user-attachments/assets/1435f728-7a7b-40c6-911a-f23a22b349f7
https://github.com/user-attachments/assets/b5117695-4417-4340-a358-e262ab5978dd
> fix(MC): safari fix for audio autoplay PD-4761

- packages/multiple-choice/controller/src/index.js
- packages/multiple-choice/docs/pie-schema.json
- packages/multiple-choice/docs/pie-schema.json.md
- packages/multiple-choice/src/index.js
- packages/pie-models/src/pie/multiple-choice/index.ts
https://illuminate.atlassian.net/browse/PD-4781
> feat(multiple-choice): separate autoplay logic from item completion when audio ends PD-4781

- packages/drag-in-the-blank/configure/src/choice.jsx
https://illuminate.atlassian.net/browse/PD-4641
> fix(ditb): fix font size for fractions in mathematical answer choices PD-4641

- packages/multiple-choice/src/index.js
https://illuminate.atlassian.net/browse/PD-4783
> feat(multiple-choice): change warning for audio autoplay with play button gif PD-4783

- packages/multiple-choice/src/index.js
https://illuminate.atlassian.net/browse/PD-4411
> fix(multiple-choice): multiple event listeners conflict on re-render PD-4411

- packages/drag-in-the-blank/docs/pie-schema.json
- packages/drag-in-the-blank/docs/pie-schema.json.md
- packages/drag-in-the-blank/src/index.js
- packages/drag-in-the-blank/src/main.js
- packages/pie-models/src/pie/drag-in-the-blank/index.ts
https://illuminate.atlassian.net/browse/PD-4791
no need to add the new props in controller, all model properties are passed to the out object in model
> feat(drag-in-the-blank): autoplay audio for STAR PD-4791

- packages/categorize/src/__tests__/__snapshots__/index.test.js.snap
- packages/categorize/src/categorize/__tests__/__snapshots__/index.test.jsx.snap
- packages/categorize/src/categorize/index.jsx
- packages/categorize/src/index.js
- packages/drag-in-the-blank/src/__tests__/__snapshots__/index.test.js.snap
- packages/drag-in-the-blank/src/index.js
- packages/drag-in-the-blank/src/main.js
- packages/hotspot/src/hotspot/index.jsx
- packages/hotspot/src/index.js
- packages/image-cloze-association/src/__tests__/__snapshots__/index.test.js.snap
- packages/image-cloze-association/src/__tests__/__snapshots__/root.test.jsx.snap
- packages/image-cloze-association/src/index.js
- packages/image-cloze-association/src/root.jsx
- packages/multiple-choice/src/index.js
- packages/multiple-choice/src/multiple-choice.jsx
https://illuminate.atlassian.net/browse/PD-4783
> fix: audio autoplay button update container PD-4783

- packages/categorize/src/index.js
- packages/drag-in-the-blank/src/index.js
- packages/hotspot/src/index.js
- packages/image-cloze-association/src/index.js
- packages/multiple-choice/src/index.js
https://illuminate.atlassian.net/browse/PD-4804
> fix: PD-4804 updated container for all autoplay-supported elements

- packages/drawing-response/src/drawing-response/__tests__/__snapshots__/container.test.jsx.snap
- packages/drawing-response/src/drawing-response/container.jsx
- packages/drawing-response/src/drawing-response/drawable-main.jsx
- packages/drawing-response/src/index.js
https://illuminate.atlassian.net/browse/PD-4739
> fix(drawing-response): fix drawing response area is cut off PD-4739

- packages/complex-rubric/controller/src/index.js
- packages/rubric/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-4833
> fix(rubric): fix validation in rubric PD-4833

- packages/multiple-choice/controller/src/index.js
- packages/multiple-choice/docs/pie-schema.json
- packages/multiple-choice/docs/pie-schema.json.md
- packages/multiple-choice/src/multiple-choice.jsx
- packages/pie-models/src/pie/multiple-choice/index.ts
https://illuminate.atlassian.net/browse/PD-4795
depending on this to work: https://github.com/pie-framework/pie-lib/pull/1704
> feat(multiple-choice): add customAudioButton PD-4795

- packages/multiple-choice/src/index.js
https://illuminate.atlassian.net/browse/PD-4853
> fix(multiple-choice): fix TypeError issue with Keyboard Events PD-4853

- packages/categorize/controller/src/index.js
- packages/categorize/docs/pie-schema.json
- packages/categorize/docs/pie-schema.json.md
- packages/categorize/src/categorize/index.jsx
- packages/pie-models/src/pie/categorize/index.ts
part of https://illuminate.atlassian.net/browse/PD-4795
> feat(categorize): add customAudioButton PD-4795

- packages/drag-in-the-blank/docs/pie-schema.json
- packages/drag-in-the-blank/docs/pie-schema.json.md
- packages/drag-in-the-blank/src/main.js
- packages/pie-models/src/pie/drag-in-the-blank/index.ts
part of https://illuminate.atlassian.net/browse/PD-4795
> feat(drag-in-the-blank): add customAudioButton PD-4795

- packages/image-cloze-association/docs/pie-schema.json
- packages/image-cloze-association/docs/pie-schema.json.md
- packages/image-cloze-association/src/root.jsx
- packages/pie-models/src/pie/image-cloze-association/index.ts
part of https://illuminate.atlassian.net/browse/PD-4795
> feat(image-cloze-association): add customAudioButton PD-4795

- packages/hotspot/controller/src/index.js
- packages/hotspot/docs/pie-schema.json
- packages/hotspot/docs/pie-schema.json.md
- packages/hotspot/src/hotspot/index.jsx
- packages/pie-models/src/pie/hotspot/index.ts
part of https://illuminate.atlassian.net/browse/PD-4795
> feat(hotspot): add customAudioButton PD-4795

- packages/categorize/src/categorize/__tests__/choice.test.jsx
- packages/categorize/src/categorize/choice.jsx
https://illuminate.atlassian.net/browse/PD-4866
> fix(categorize): Tokens cannot be dragged when touch and hold  for some time  into the response area

- packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-4874
> fix(math-inline): ensure mqStatic retains last valid reference PD-4874

- packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-4874
> fix(math-inline): Fix input focus detection when mqStatic is undefined PD-4874

- packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-4907
> fix(math-inline): Fix duplicate event listeners and improve focus detection PD-4907

- packages/explicit-constructed-response/configure/src/ecr-toolbar.jsx
https://illuminate.atlassian.net/browse/PD-4913
> fix(ECR): Fix correct answer field to treat HTML as literal text PD-4913

- packages/explicit-constructed-response/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-4912
> fix(ECR): fix scoring errors PD-4912

- packages/image-cloze-association/src/image-drop-target.jsx
- packages/match-list/src/answer.js
- packages/placement-ordering/src/tile.jsx
https://illuminate.atlassian.net/browse/PD-4888
> fix: match-list, placement-ordering, ica Tokens cannot be dragged when touch and hold for some time into the response area PD-4888

- packages/categorize/src/index.js
- packages/drag-in-the-blank/src/index.js
- packages/hotspot/src/index.js
- packages/image-cloze-association/src/index.js
- packages/multiple-choice/src/index.js
https://illuminate.atlassian.net/browse/PD-4938
> feat: use optimized enable autoplay audio image from pie-lib PD-4938

- packages/categorize/src/categorize/choice.jsx
https://illuminate.atlassian.net/browse/PD-4978
> fix(categorize): fix multiple dnd backend issue PD-4978

- packages/passage/src/stimulus-tabs.jsx
https://illuminate.atlassian.net/browse/PD-4594
same styling that is used in prompt tables and response area tables
> fix(passage): fix table styling inside passage to be consistent PD-4594

- packages/multiple-choice/src/choice-input.jsx
https://illuminate.atlassian.net/browse/PD-4555
> fix(multiple-choice): enhance visible focus indicator, improving contrast and user experience PD-4555

- packages/multiple-choice/src/choice-input.jsx
https://illuminate.atlassian.net/browse/PD-4557
> fix(multiple-choice): add aria label for answers with math, LaTeX, or images PD-4557

- packages/image-cloze-association/src/image-container.jsx
https://illuminate.atlassian.net/browse/PD-5046
> fix(image-cloze-association): remove confusing alt text PD-5046

- packages/rubric/configure/src/__tests__/index.test.jsx
- packages/rubric/configure/src/index.js
- packages/rubric/configure/src/pie-toolbox-rubric/authoring.jsx
https://illuminate.atlassian.net/browse/PD-4832
> fix(rubric): disable and set excludeZero to false when maxPoints is 1 PD-4832

- packages/multiple-choice/src/choice-input.jsx
- packages/multiple-choice/src/choice.jsx
- packages/multiple-choice/src/multiple-choice.jsx
https://illuminate.atlassian.net/browse/PD-4562
> fix(ebsr): add name attribute to radio buttons to correctly group radio buttons and trap arrow navigation PD-4562

- packages/multi-trait-rubric/configure/src/index.js
- packages/multi-trait-rubric/configure/src/main.jsx
- packages/multi-trait-rubric/configure/src/utils.js
- packages/multi-trait-rubric/docs/demo/generate.js
https://illuminate.atlassian.net/browse/PD-4832
> fix(multi-trait-rubric): disallow use of Exclude Zero when Max Points is 1 PD-4832

- pslb/pslb.config.js
https://illuminate.atlassian.net/browse/PD-5085
> feat: update pie-toolbox-module PD-5085

- packages/rubric/src/main.jsx
https://illuminate.atlassian.net/browse/PD-5091
Before:
After:
> fix(rubric): enhance table styles for better UI consistency PD-5091

- packages/multiple-choice/src/choice-input.jsx
- packages/multiple-choice/src/choice.jsx
- packages/multiple-choice/src/multiple-choice.jsx
https://illuminate.atlassian.net/browse/PD-4562
> fix: add arrow key navigation for checkbox groups, focus first input when tabbing into group

- packages/categorize/configure/src/index.js
https://illuminate.atlassian.net/browse/PD-5097
pie-lib PR: https://github.com/pie-framework/pie-lib/pull/1885
> fix(categorize): call render in connectedCallback to ensure math is rendered, remove redundant renderMath calls PD-5097

- packages/multiple-choice/src/multiple-choice.jsx
https://illuminate.atlassian.net/browse/PD-4563?focusedCommentId=1994296
> fix: remove default outline from fieldset on focus PD-4563
