packages/categorize/configure/src/design/choices/choice.jsx, packages/categorize/configure/src/design/choices/index.jsx, packages/categorize/configure/src/design/index.jsx, packages/categorize/configure/src/design/input-header.jsx, packages/categorize/configure/src/index.js, packages/categorize/configure/src/main.jsx
This is for the [Issue 85](https://github.com/pie-framework/pie-elements/issues/85).
placement-ordering already has image support in choices
=> feat(categorize): added image support for categorize choices

packages/ebsr/configure/src/index.js, packages/ebsr/controller/src/__tests__/index.test.js, packages/ebsr/controller/src/index.js
* first part can be only a single-correct MC
* second part defaults to MC, but can be changed to MS
* if the first part is incorrect, the score for the second one defaults to zero
* if the first part is correct, the second is scored like a stand-alone MS item (including partial scoring)
=> feat: update scoring [ch1199]

packages/drag-in-the-blank/configure/src/defaults.js, packages/drag-in-the-blank/configure/src/main.jsx, packages/drag-in-the-blank/controller/src/index.js, packages/explicit-constructed-response/configure/src/defaults.js, packages/explicit-constructed-response/configure/src/main.jsx, packages/explicit-constructed-response/controller/src/index.js, packages/inline-dropdown/configure/src/defaults.js, packages/inline-dropdown/configure/src/main.jsx, packages/inline-dropdown/controller/src/index.js
Add rationale support for ECR, Drag in the Blank, Inline Dropdown.
Noticed that all above interactions already had `rationale` inside docs.
Issue reported [here](https://app.clubhouse.io/keydatasystems/story/2626/several-item-types-rationale-missing-from-settings-panel-and-when-toggled-on-item-authoring).
=> Add rationale support for several Item Types

packages/ebsr/configure/src/index.js
Issue reported [here](https://app.clubhouse.io/keydatasystems/story/2545/ebsr-needs-an-authoring-view-setting-for-feedback).
=> fix: config settings

packages/image-cloze-association/controller/src/__tests__/index.test.js, packages/image-cloze-association/controller/src/index.js, packages/image-cloze-association/controller/src/utils.js
Outcome fix: there should only be deductions to the extent that the student placed more objects than were in the correct response.
This branch was created from `sergiulucaci/ch1955/ica-alternate-correct-answers`, so make sure you review and merge after #284.
=> ICA: fixes for partial scoring 

packages/select-text/controller/src/__tests__/index.test.js, packages/select-text/controller/src/index.js
Issue reported [here](https://app.clubhouse.io/keydatasystems/story/2289/select-text-partial-credit-scoring-does-not-apply-necessary-deductions-when-needed).
=> fix: apply scoring deductions

packages/categorize/controller/src/index.js, packages/drag-in-the-blank/controller/src/index.js, packages/ebsr/controller/src/index.js, packages/explicit-constructed-response/controller/src/index.js, packages/function-entry/controller/src/index.js, packages/graphing/controller/src/index.js, packages/hotspot/controller/src/index.js, packages/image-cloze-association/controller/src/index.js, packages/inline-choice/controller/src/index.js, packages/inline-dropdown/controller/src/index.js, packages/match-list/controller/src/index.js, packages/match/controller/src/index.js, packages/math-inline/controller/src/index.js, packages/multiple-choice/controller/src/index.js, packages/number-line/controller/src/index.js, packages/placement-ordering/controller/src/index.js, packages/point-intercept/controller/src/index.js, packages/select-text/controller/src/index.js, packages/text-entry/controller/src/index.js
If the result from `createCorrectResponseSession` is passed to the player via `session` setter,  question should be filled with the correct answers of the question. 
Example:
```
const player = document.querySelector('hotspot-element');
createCorrectResponseSession(question, env).then(session => {
player.session = session;  
});
```
Requirements presented [here](https://app.clubhouse.io/keydatasystems/story/2885/add-createcorrectresponsesession-to-controller-for-all-pie-elements).
Let me know if this approach looks good to you, so I can add tests (I assume this method should require tests, right?) and clean the commit history.
=> Add “correct answer indication” controller method 

packages/math-inline/docs/demo/generate.js
Removing text nodes from default model. Takes care of [ch3489] partially. Still investigating mathquill fix needed for text node interactions.
=> chore: math-inline default model update

packages/hotspot/configure/src/hotspot-palette.jsx
Small fix here. React freaked out when the "incorrect" prop type was provided.
=> fix(hotspot): hotspotList prop type is array, not string

packages/select-text/configure/src/__tests__/__snapshots__/design.test.jsx.snap, packages/select-text/configure/src/design.jsx
Should fix [3558](https://app.clubhouse.io/keydatasystems/story/3558/select-text-partial-scoring-should-be-in-settings).
=> feat(select-text): move partial scoring to settings panel

packages/explicit-constructed-response/configure/src/alternateResponses.jsx, packages/explicit-constructed-response/configure/src/index.js, packages/explicit-constructed-response/configure/src/main.jsx, packages/explicit-constructed-response/controller/src/__tests__/index.spec.js, packages/explicit-constructed-response/controller/src/index.js
The item details are disappearing if we click on Show correct answer button for ECR item.
Another issue found that was causing app crash: Clear the "Define Template, Choices, and Correct Responses" Input, focus somewhere else, click twice on "+ Response Area", focus inside the  "Define Template, Choices, and Correct Responses" Input and click on the Done checkmark => app crash.
=> fix: ch4723:

packages/math-inline/controller/package.json, packages/math-inline/controller/src/__tests__/index.test.jsx, packages/math-inline/controller/src/index.js, yarn.lock
* math-evaluator uses the new @pie-framework/math-expressions to handle
unknown latex commands. [See math-expressions change][me]
[me]: https://github.com/pie-framework/math-expressions/pull/1
=> fix: PIE-188 - upgrade @pie-lib/math-evaluator@^0.6.0

packages/select-text/configure/src/__tests__/__snapshots__/design.test.jsx.snap, packages/select-text/configure/src/__tests__/design.test.jsx, packages/select-text/configure/src/design.jsx, packages/select-text/controller/src/__tests__/index.test.js, packages/select-text/controller/src/index.js
Removed html entities from text in order to prevent having issues with tokens  offsets.
=> fix: 4210: Select Text token alignment issues with some legacy content

packages/hotspot/configure/src/__tests__/__snapshots__/hotspot-container.test.js.snap, packages/hotspot/configure/src/__tests__/__snapshots__/hotspot-drawable.test.js.snap, packages/hotspot/configure/src/__tests__/hotspot-drawable.test.js, packages/hotspot/configure/src/defaults.js, packages/hotspot/configure/src/hotspot-container.jsx, packages/hotspot/configure/src/hotspot-drawable.jsx, packages/hotspot/configure/src/hotspot-polygon.jsx, packages/hotspot/configure/src/hotspot-rectangle.jsx, packages/hotspot/configure/src/root.jsx, packages/hotspot/controller/src/index.js, packages/hotspot/docs/pie-schema.json, packages/hotspot/docs/pie-schema.json.md, packages/pie-models/src/pie/hotspot/index.ts
For some hotspot items, the distinction between selected and not selected areas is quite subtle (increased border width)
=> fix: ch2880

packages/ebsr/configure/src/__tests__/__snapshots__/index.test.js.snap, packages/ebsr/configure/src/__tests__/index.test.js, packages/ebsr/configure/src/defaults.js, packages/ebsr/configure/src/index.js, packages/ebsr/configure/src/main.jsx, packages/ebsr/controller/src/__tests__/index.test.js, packages/ebsr/controller/src/index.js, packages/ebsr/docs/config-schema.json, packages/ebsr/docs/config-schema.json.md, packages/ebsr/docs/pie-schema.json, packages/ebsr/docs/pie-schema.json.md, packages/pie-models/src/pie/ebsr/index.ts
fix for Dichotomous scoring type: EBSR should be scored as 1/1 if both parts are correct, and as 0/1 if either part is wrong.
BREAKING CHANGE: replaced `model.partA.partialScoring` and `model.partB.partialScoring` with `model.partialScoring`, replaced `model.partA.scoringType` and `model.partB.scoringType` with `model.scoringType`, replaced `configuration.partA.partialScoring` and `configuration.partB.partialScoring` with `configuration.partialScoring`, replaced `configuration.partA.scoringType` and `configuration.partB.scoringType` with `configuration.scoringType`
feat: ch4719: Scoring settings for EBSR are not correct (partial scoring).
Updated docs.
=> fix: ch6025: 

packages/select-text/configure/src/__tests__/__snapshots__/design.test.jsx.snap, packages/select-text/configure/src/__tests__/design.test.jsx, packages/select-text/configure/src/design.jsx, packages/select-text/controller/src/__tests__/index.test.js, packages/select-text/controller/src/index.js, packages/select-text/docs/demo/config.js, packages/select-text/docs/demo/generate.js, packages/select-text/docs/demo/index.html
fix: html does not need to be removed on front-end (this was a fix for one issue, but it causes other issues); the main issue will be fixed on back-end (don't parse the html when loading an item to prevent token start & end issues)
=> Ready to be merged

packages/drag-in-the-blank/configure/src/__tests__/__snapshots__/main.test.jsx.snap, packages/drag-in-the-blank/configure/src/main.jsx, packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/main.test.jsx.snap, packages/explicit-constructed-response/configure/src/main.jsx, packages/inline-dropdown/configure/src/__tests__/__snapshots__/main.test.jsx.snap, packages/inline-dropdown/configure/src/main.jsx
The response template formatting toolbar should behave like other PIE formatting toolbars: it should appear only when the field with which it is associated has focus. This applies to the following item types: explicit-constructed-response, inline-dropdown, drag-in-the-blank.
PD-142.
=> fix: Toolbar visible only on focus - PD-142.

packages/multiple-choice/controller/src/__tests__/index.test.js, packages/multiple-choice/controller/src/index.js
Remove unintended clue about how many answer choices are correct.
This requires update of pie-ui/multiple-choice after PR is merged: https://github.com/pie-framework/pie-ui/pull/207
PD-253
=> fix: Multiple Select should report a question as "answered" as soon as a selection has been made PD-253

packages/explicit-constructed-response/controller/src/index.js
(Use rsponseAreas to determine the max score instead of choices number).
=> fix: In LP, erroneous score data being returned for some ECRs. PD-570

packages/explicit-constructed-response/configure/src/__tests__/markupUtils.test.jsx, packages/explicit-constructed-response/configure/src/__tests__/utils.test.js, packages/explicit-constructed-response/configure/src/markupUtils.js, packages/explicit-constructed-response/docs/demo/generate.js
PD-338: feat(markup): made sure brs are not removed anymore since they are handled in editable html
=> PD-338: feat(markup): made sure brs are not removed anymore since they are handled in editable html

packages/explicit-constructed-response/configure/src/__tests__/markupUtils.test.jsx, packages/explicit-constructed-response/configure/src/markupUtils.js
1. Added a fix for regex where \\t won't get removed for \\times, which is required for multiplication symbol.
=> fix: modified regex to handle multiplication symbol issue PD-367

packages/math-inline/controller/src/__tests__/index.test.jsx, packages/math-inline/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-810
=> fix(math-inline): don't include rationale and teacher instructions in the item configuration for student gather - PD-810

packages/placement-ordering/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-1002
=> PD-1002 fix: Shuffle choices only if user is in gather mode. (at evaluate, at least, the order is important)

packages/number-line/controller/src/__tests__/index.test.js, packages/number-line/controller/src/index.js, packages/number-line/src/number-line/index.jsx
https://illuminate.atlassian.net/browse/PD-1012
=> fix: If a Number Line element has no correct answer, Evaluate mode should just show the student's response without any markup PD-1012

packages/placement-ordering/controller/src/__tests__/index.test.js, packages/placement-ordering/controller/src/index.js, packages/placement-ordering/docs/demo/generate.js, packages/placement-ordering/docs/demo/session.js
https://user-images.githubusercontent.com/20281464/111593720-ea606580-87d2-11eb-9a66-ff3b26b31294.mov
https://user-images.githubusercontent.com/20281464/111593955-2abfe380-87d3-11eb-997c-40ed23b8fe69.mov
As you can see, previously, the session.value was always being set for placementArea: true.
Since that is incorrect, I removed it (only for placementArea: true)
=> fix: Do not set session.value if placementArea is true.

packages/math-inline/docs/demo/generate.js, packages/math-inline/docs/demo/session.js, packages/math-inline/src/index.js
Apparently, math-inline **doesn't update the session object, but replaces it** with an entirely new object (different address).
Because of this, the _session in catalog-demo does not get updated (check video):
https://user-images.githubusercontent.com/20281464/111614514-5a2d1b00-87e8-11eb-9f45-713aec98b272.mov
In order to fix this, I'm just updating session properties, without updating the entire object:
https://user-images.githubusercontent.com/20281464/111615071-ffe08a00-87e8-11eb-8629-982f262cce8c.mov
Issue found while investigating https://illuminate.atlassian.net/browse/PD-385
=> fix: Instead of resetting the entire session object, update its properties.

packages/graphing/src/main.jsx
See [PD-575](https://illuminate.atlassian.net/browse/PD-575) issue.
This is the quickest solution and I’ve opted to make it so because for “correct” and “incorrect” answers we have only one color (correct-color or incorrect-color).
In order to have 4 shades of green we could add a new property for pie-lib/graphing of `showingCorrect` and depending on that we show those 4 colors. Also, if we do this it would be indicate to add 4 shades of colors for “correct” or “incorrect” answers as well.
=> fix(graphing) set correct colors in "showing-correct" state

packages/placement-ordering/configure/src/__tests__/__snapshots__/design.test.jsx.snap, packages/placement-ordering/configure/src/defaults.js, packages/placement-ordering/configure/src/design.jsx, packages/placement-ordering/controller/src/__tests__/index.test.js, packages/placement-ordering/controller/src/defaults.js, packages/placement-ordering/controller/src/index.js, packages/placement-ordering/docs/demo/generate.js
For Placement Ordering, remove the lockChoiceOrder setting from the model and authoring
https://illuminate.atlassian.net/browse/PD-351
=> feat(placement-ordering): remove lockChoiceOrder from model and authoring PD-351

packages/pie-models/src/pie/placement-ordering/index.ts, packages/placement-ordering/configure/src/__tests__/__snapshots__/design.test.jsx.snap, packages/placement-ordering/configure/src/defaults.js, packages/placement-ordering/configure/src/design.jsx, packages/placement-ordering/controller/src/defaults.js, packages/placement-ordering/controller/src/index.js, packages/placement-ordering/docs/config-schema.json, packages/placement-ordering/docs/config-schema.json.md, packages/placement-ordering/docs/pie-schema.json, packages/placement-ordering/docs/pie-schema.json.md, packages/placement-ordering/src/placement-ordering.jsx, packages/placement-ordering/src/tiler.jsx
Removed choices label dummy value and fixed choices label toggle functionality
BREAKING CHANGE: Removed choiceLabel.enabled from configuration and added to the model
https://illuminate.atlassian.net/browse/PD-1147
=> fix(placement-ordering): Fixed Placement Ordering items are displaying an incorrect label - PD-1147

packages/drawing-response/configure/src/__tests__/__snapshots__/root.test.jsx.snap, packages/drawing-response/configure/src/defaults.js, packages/drawing-response/configure/src/root.jsx, packages/drawing-response/docs/demo/generate.js, packages/drawing-response/docs/pie-schema.json, packages/drawing-response/docs/pie-schema.json.md, packages/pie-models/src/pie/drawing-response/index.ts
=> feat(drawing-response) : added option for toolbar editor position

packages/drag-in-the-blank/configure/src/__tests__/__snapshots__/main.test.jsx.snap, packages/drag-in-the-blank/configure/src/choices.jsx, packages/drag-in-the-blank/configure/src/defaults.js, packages/drag-in-the-blank/configure/src/main.jsx, packages/drag-in-the-blank/docs/demo/generate.js, packages/drag-in-the-blank/docs/pie-schema.json, packages/drag-in-the-blank/docs/pie-schema.json.md, packages/pie-models/src/pie/drag-in-the-blank/index.ts
feat(drag-in-the-blank) : added option for setting the toolbar editor position.
@alextkd
=> feat(drag-in-the-blank) :  toolbar editor position

packages/explicit-constructed-response/configure/src/__tests__/__snapshots__/main.test.jsx.snap, packages/explicit-constructed-response/configure/src/defaults.js, packages/explicit-constructed-response/configure/src/main.jsx, packages/explicit-constructed-response/docs/demo/generate.js, packages/explicit-constructed-response/docs/pie-schema.json, packages/explicit-constructed-response/docs/pie-schema.json.md, packages/pie-models/src/pie/explicit-constructed-response/index.ts
feat(explicit-constructed-response) : added option to set toolbar editor position
@alextkd
=> feat(explicit-constructed-response) : toolbar editor position

packages/math-inline/configure/src/__tests__/__snapshots__/configure.test.js.snap, packages/math-inline/configure/src/configure.jsx, packages/math-inline/configure/src/defaults.js, packages/math-inline/configure/src/general-config-block.jsx, packages/math-inline/docs/demo/generate.js, packages/math-inline/docs/pie-schema.json, packages/math-inline/docs/pie-schema.json.md, packages/pie-models/src/pie/math-inline/index.ts
=> feat(math-inline): added option to set toolbar editor position

packages/pie-models/src/pie/select-text/index.ts, packages/select-text/configure/src/defaultConfiguration.js, packages/select-text/configure/src/design.jsx, packages/select-text/docs/demo/generate.js, packages/select-text/docs/pie-schema.json, packages/select-text/docs/pie-schema.json.md
=> feat(select-text) : added option to set toolbar editor position

packages/image-cloze-association/src/possible-response.jsx
https://illuminate.atlassian.net/browse/PD-1244
=> fix(image-cloze-association): Moved the evaluate symbol to fit in the available content PD-1244

packages/number-line/src/index.js, packages/number-line/src/number-line/index.jsx
- apply initial elements if session is undefined, so that initial view will work in pits
- fix: initial view - it should not be possible to plot the same point or other object multiple times
=> fix(number-line): initial view should render correctly in pits

packages/passage/package.json, packages/passage/src/__tests__/__snapshots__/stimulus-tabs.test.jsx.snap, packages/passage/src/print.js, packages/passage/src/stimulus-tabs.jsx
Rendered tabs in sequence for more than one passage:
View with only one passage:
=> feat(passage): implement print PD-1282

packages/math-inline/controller/package.json, yarn.lock
fix latex to ast conversion for logarithms
=> chore: bump math-validation version

packages/hotspot/src/hotspot/index.jsx
User will be able to scale back to 1 by removing `--pie-zoom` property. Not reported yet by a tester but it's good to have it.
https://illuminate.atlassian.net/browse/PD-360
=> fix(hotspot): add support for removing --pie-zoom css property PD-360

packages/multiple-choice/src/choice-input.jsx, packages/multiple-choice/src/choice.jsx
- labels (letters/numbers) are closer to the controls (radio/checkbox)
- answer choices are closer to their labels
- added whitespace to the end of each choice
=> fix/PD-1677: MC Horizontal Layout Tweaks

packages/number-line/src/number-line/graph/elements/ray.jsx
Correct and incorrect arrow colors should now match the ray color.
=> fix/PD-1770: Number line design treatment of rays in Evaluate

packages/charting/configure/package.json, packages/charting/package.json
BREAKING CHANGE: The editCategoryEnabled checkbox and property was removed.
Enabled property will be used for each category.
=> feat(charting): remove editCategoryEnabled property checkbox and usage.

packages/multiple-choice/configure/src/defaults.js, packages/multiple-choice/configure/src/index.js, packages/multiple-choice/configure/src/main.jsx, packages/multiple-choice/controller/src/index.js, packages/multiple-choice/docs/config-schema.json, packages/multiple-choice/docs/config-schema.json.md, packages/multiple-choice/docs/pie-schema.json, packages/multiple-choice/docs/pie-schema.json.md, packages/multiple-choice/package.json, packages/multiple-choice/src/multiple-choice.jsx, packages/pie-models/src/pie/multiple-choice/index.ts, yarn.lock
apparently multiple-choice was left out during implementing translations, so I added them now. 
The correct answer toggle is the only affected UI label in player
=> feat(multiple-choice): add translations

packages/match/configure/src/configure.jsx
https://illuminate.atlassian.net/browse/PD-3234
Add row ID validation to Configure component
- Introduced `validateRowsID` function to ensure row IDs are sequential and unique.
- Implemented ID validation logic in `componentDidMount` to correct any inconsistencies in the row IDs upon component mount.
Refactor rowIdCounter initialization to ensure highest id value
- Calculate maxId from all rows instead of relying on the last row's id.
- Add checks to handle potential cases where props.model.rows is undefined or empty.
- Set rowIdCounter to maxId + 1, ensuring a unique and sequential id.
This addition ensures that row IDs in the Configure component are always consistent and avoids potential issues with duplicate or missing IDs.
=> fix(match): Introduced  function to ensure row IDs are sequential and unique. PD-3234

packages/charting/configure/src/__tests__/__snapshots__/configure.test.js.snap, packages/charting/configure/src/defaults.js, packages/charting/docs/demo/generate.js, packages/charting/docs/pie-schema.json, packages/charting/docs/pie-schema.json.md, packages/pie-models/src/pie/charting/index.ts
https://illuminate.atlassian.net/browse/PD-3216
Update default behavior of charting authoring UI properties
- Set default values for `changeInteractiveEnabled`, `changeEditableEnabled`, and `changeAddCategoryEnabled` to false.
- Ensures consistent authoring UI behavior when these properties are not explicitly set.
- Update docs accordingly.
=> feat(charting): Update default behavior of charting authoring UI properties. Update docs accordingly. PD-3216

packages/number-line/configure/src/__tests__/__snapshots__/main.test.jsx.snap, packages/number-line/configure/src/defaults.js, packages/number-line/configure/src/domain.jsx, packages/number-line/configure/src/main.jsx, packages/number-line/configure/src/point-config.jsx, packages/number-line/configure/src/ticks.jsx, packages/number-line/src/number-line/index.jsx
Fixed number line issue as per SC-28651/SC-28674
1. Fix when domain min and max are same screen gets blank
2. Added min and max for number text field.
3. Ticks model not getting set after saving item.
4. Changed default tickintervaltype to decimal to accommodate legacy NL items.
5. AvailableTypes not getting loaded correctly after saving Item
=> fix(number-line): Fix issue with domain and ticks as per SC-28651

packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-2448
Choosing to add aria-hidden="true" to elements with the class .mq-selectable instead of using display: none is primarily about maintaining functionality and visibility for sighted users while ensuring that these elements are not accessible to screen readers. Here's a brief explanation of the considerations:
In the context of MathQuill or similar math rendering libraries, elements with the class .mq-selectable might be part of the interactive math input experience. They might be necessary for sighted users to interact with or visually parse the mathematical content. Using aria-hidden="true" allows these elements to remain functional and part of the interactive experience for sighted and keyboard-only users, while ensuring they do not create …
=> feat(math-inline): Implement aria-hidden to exclude MathQuill selectable elements from screen reader accessibility PD-2448

packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-2482
- Modified `updateAria` to dynamically add screen-reader-only instructions span before each textarea.
- Ensured textareas are properly described by associating them with the instructions via `aria-describedby`.
- Improved accessibility by updating `aria-hidden` for `.mq-selectable` elements and providing context for math keypad input.
- Ensure screen-reader instructions are read when using keyboard (tab) to navigate the player
=> feat(math-inline): Add aria-describedby and screen-reader-only instructions to textarea in MER response areas PD-2482

packages/math-templated/src/main.jsx
Feedback in only defined in controller and print does not use controller. So, a sanity check is needed to fix the issue
https://illuminate.atlassian.net/browse/PD-3893
=> fix(math-templated): print not working for instructor PD-3893

packages/placement-ordering/src/tile.jsx
https://illuminate.atlassian.net/browse/PD-3946
Based on George's comment regarding the placement-ordering in which only the "target" area should have the dashed border, I needed to send the type to Placeholder in order to apply different styles.
=> feat(placement-ordering): send type to placeholder in order to apply styles differently PD-3946

packages/image-cloze-association/src/interactive-section.jsx
https://illuminate.atlassian.net/browse/PD-3658
Without the fit-content:
After the fix:
=> fix(ICA): Refactored interactive styles to reduce duplication and added 'width: fit-content' PD-3658

packages/math-inline/src/main.jsx
Previous styling (flex:2 and flex: 8) was prone to error since it would cause the "R" box to expand and not have a fixed width
We want to keep the "R" box the same width always, only content + padding and let all the available space for the math input
https://illuminate.atlassian.net/browse/PD-4024
=> fix(math-inline): tweak flex style in order to fix PD-4024

packages/categorize/src/categorize/choice.jsx
https://illuminate.atlassian.net/browse/PD-3652
The primary goal behind this change was to address an issue on touch devices when interacting with image-based tokens in categorize element. There was a problem where a long press on the image—intended to trigger a drag-and-drop action— caused the browser to respond with a default gesture showing a green plus icon, indicating that it was trying to open the image in a new tab.
Specifically, a long press on the image led to the creation of a new DOM node (an "image-overlay"). To prevent this unwanted interaction, I added the CSS property pointerEvents: 'none'. By doing so, I disabled pointer events for the images, stopping the context menu or other interactions from being triggered during a long press. This solution solved the problem by …
=> fix(categorize): added pointerEvents none for categorize card to prevent other interactions with touch events PD-3652

packages/placement-ordering/src/tile.jsx
This PR addresses the issue where drag-and-drop functionality was broken in Chrome versions 106 and later. After in-depth investigation, the root cause was found to be related to Chrome's rendering engine changes in v106, which affected React DnD's handling of drag events.
A workaround has been applied by adding translateZ(0) to the body, forcing Chrome to use hardware-accelerated rendering, which resolves the issue.
For full details regarding the issue, root cause, and fixes, please refer to the comments section in
https://illuminate.atlassian.net/browse/PD-3656
=> fix(placement-ordering): Added translateZ(0) to body to resolve rendering issues in Chrome v106+ for drag n drop PD-3656

packages/math-inline/src/__tests__/main.test.js, packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/DNA-22415
https://illuminate.atlassian.net/browse/PD-4155
- Fixed an issue where the math editor was closing unexpectedly when students clicked on the keypad buttons during input.
- Added checks to handle the focus state of the input field more reliably, ensuring proper handling of keyboard interactions like `ArrowDown` and click events.
- Optimized the `handleKeyDown` logic to reduce redundant state updates and improve performance.
=> fix(math-inline): resolve issue where math editor closes when interacting with the keypad PD-4155 DNA-22415

packages/categorize/configure/src/design/categories/category.jsx, packages/categorize/configure/src/index.js
https://illuminate.atlassian.net/browse/PD-4283 
**_Before:_**
_**category label defined like this:**_
**_was rendering like this in the alternate section:_**
**_After:_**
=> fix(categorize): title in alternate section not rendering rows and math PD-4283

packages/graphing/controller/src/index.js
Filtering incomplete graph objects added by student before scoring. This is the case when student add some graph object and click undo and object is in building state.
Jira - [https://illuminate.atlassian.net/browse/SC-33160](https://illuminate.atlassian.net/browse/SC-33160)
=> fix(graphing): Filtering incomplete graph objects added by student before scoring.

packages/image-cloze-association/src/image-container.jsx, packages/image-cloze-association/src/image-drop-target.jsx, packages/image-cloze-association/src/root.jsx
https://illuminate.atlassian.net/browse/PD-4386
Following George's suggestion, adjusted the response container's default behavior to apply "responseContainerPadding": "0px" when "max_response_per_zone" is either absent or set to 1. ( in code, if maxResponsePerZone is absent is automatically set to 1 )
Before:
After:
=> fix(ica): Misalignment of answer choices and response areas PD-4386

packages/number-line/src/number-line/graph/elements/point.jsx
https://illuminate.atlassian.net/browse/PD-4015
Set pointer-events to visibleStroke on endpoint circles to prevent them from blocking clicks on the line
This allows interactions with the visible stroke of the circle without interfering with line selection
=> fix(number-line): select a segment or ray near endpoints PD-4015

packages/hotspot/docs/demo/generate.js, packages/hotspot/src/hotspot/circle.jsx, packages/hotspot/src/hotspot/polygon.jsx, packages/hotspot/src/hotspot/rectangle.jsx
rectangular shape for hover: https://illuminate.atlassian.net/browse/PD-4367
select bug on hover: https://illuminate.atlassian.net/browse/PD-4492
https://github.com/user-attachments/assets/d0c44c8f-a2ab-46d2-876f-b1f43955fe51
=> fix(hotspot): use rectangular shape for all hover shapes, show select outline when hover is in effect and selected PD-4492, PD-4367

packages/multiple-choice/controller/src/index.js, packages/multiple-choice/docs/demo/generate.js, packages/multiple-choice/docs/pie-schema.json, packages/multiple-choice/docs/pie-schema.json.md, packages/multiple-choice/src/choice-input.jsx, packages/multiple-choice/src/choice.jsx, packages/multiple-choice/src/multiple-choice.jsx, packages/pie-models/src/pie/multiple-choice/index.ts
If this new added property is true, the selection button and choice prefix will be positioned below the corresponding answer choice.
https://illuminate.atlassian.net/browse/PD-3842
for vertical layout
for grid layout
for horizontal layout
=> feat(multiple-choice): use isSelectionButtonBelow for choice prefix and button position PD-3842

packages/image-cloze-association/src/possible-response.jsx
https://illuminate.atlassian.net/browse/PD-4553
Issue:
On touch devices, specifically iPads using Chrome, dragging an image within a draggable container triggered unwanted behaviors:
Context Menu: Long-pressing on the image would bring up the browser’s context menu or the image itself being opened in a new tab.
Solution: 
I've applied the following CSS rule:
'& span img': {
pointerEvents: 'none',
}
Explanation:
Ensures the image doesn't receive pointer events, avoiding context menus and unintended opening in a new tab.
Keeps the wrapping div fully draggable as intended.
Resolves touch-specific issues without additional event handling logic.
=> fix(ica): Fix Chrome behavior on iPads for image cloze association PD-4553

packages/drag-in-the-blank/configure/src/choice.jsx
Findings: https://illuminate.atlassian.net/browse/PD-4394
Fix: Prevent sentence break in authoring view when an image is uploaded at the end of a sentence.
=> fix(ditb): Prevent sentence break in authoring view with images PD-4394

packages/placement-ordering/configure/src/design.jsx
https://illuminate.atlassian.net/browse/PD-4591
=> fix(placement-ordering): conditionally add autoWidthToolbar to accommodate toolbar buttons when placementArea is true

packages/math-inline/src/__tests__/simple-question-block.test.js, packages/math-inline/src/simple-question-block.jsx
https://illuminate.atlassian.net/browse/PD-4604
The sanity check was actually triggering the updateLatex method in `Input` since the session needs to be undefined or null in order to be marked as "not answered". 
No need for a sanity check here
=> fix(math-inline): fix session save being called on render PD-4604

packages/explicit-constructed-response/configure/src/index.js
https://illuminate.atlassian.net/browse/PD-4686
=> fix(ECR): fix disable/enable spanish input for student view PD-4686

packages/categorize/src/index.js, packages/drag-in-the-blank/src/index.js, packages/hotspot/src/index.js, packages/hotspot/src/session-updater.js, packages/multiple-choice/src/session-updater.js
Changes:
- capture waitTime in hotspot and drag-in-the-blank
- store waitTime in milliseconds, instead of seconds (removed conversion to seconds)
=> Fix wait time calculations

packages/categorize/src/categorize/__tests__/choice.test.jsx, packages/categorize/src/categorize/choice.jsx
https://illuminate.atlassian.net/browse/PD-4763
The fix involves checking the drag movement. If the movement is less than a small threshold (5px), endDrag is prevented from removing the item. This ensures long press without movement won't trigger item removal by mistake.
=> fix(categorize): on touch devices on long press do not remove choice PD-4763

packages/math-inline/src/main.jsx
https://illuminate.atlassian.net/browse/PD-4882
Refactor `handleKeyDown` for improved readability & fix arrow key behavior in math editor
- Refactored `handleKeyDown` to enhance readability, remove redundant assignments, and ensure proper state updates.
- Improved event handling by destructuring key and event type.
- Ensured `setState` is updated before executing dependent logic.
Fix:
- Adjusted down arrow key behavior in the math editor.
- Now, pressing ArrowDown moves the cursor to the denominator as expected.
- The focus shifts to the first keypad element **only if the keypad was not already visible**.
=> fix(math-inline): Refactor handleKeyDown for improved readability & fix arrow key behavior in math editor PD-4882

packages/multiple-choice/src/multiple-choice.jsx
https://illuminate.atlassian.net/browse/PD-4562
We observed two main accessibility issues in this EBSR item:
Arrow key navigation was not trapped within each radio group. Users could move from one group to the next using arrow keys, which violates expected radio group behavior—navigation with arrow keys should stay within a group, and only Tab should move between groups.
The second group of radio buttons was not tabbable at all. This was caused by a custom component structure where the actual radio inputs were wrapped in spans, breaking the native focus behavior expected by the browser and Material UI.
To address the second issue, we added tabindex="0" to the <fieldset> of each group. This allows keyboard users to tab into each radio group as expected. Arrow trapping is still under …
=> fix(ebsr): allow tabbing into second radio group, fix behavior of radio button groups PD-4562

packages/math-inline/controller/src/index.js
https://illuminate.atlassian.net/browse/PD-4848
=> fix: allow math-inline scoring to continue even if one alternate answer fails parsing PD-4848

packages/math-inline/controller/package.json, packages/math-templated/controller/package.json, yarn.lock
https://illuminate.atlassian.net/browse/PD-5052
This fix addresses an issue where symbolic validation incorrectly rejected answers that included both leading spaces and trailing zeros (e.g., " 1.30").
The new logic ensures numerical equivalence is preserved regardless of surrounding whitespace and insignificant decimal padding.
Added extensive tests to confirm correct behavior for digits 0–9, including edge cases with negative numbers and leading zero values.
=> fix: bump math-validation PD-5052
